# Pandas 核心数据类型

## 什么是Pandas
- pandas是python语言的一个扩展程序库，用于数据分析。
- pandas提供了高性能、易用的数据结构和数据分析工具，使得数据分析变得更加简单和高效。
- pandas一个强大的分析结构化数据的工具集，基础是NumPy（提供高性能的矩阵运算）
- pandas可以从各种文件格式比如CSV、Excel、SQL数据库等中读取数据
- pandas可以对各种数据进行运算操作，比如归并、再成形、选择、还有数据清洗和数据加工特征

#### pandas的主要数据结构
- Series: 一维标签化数组，可以存储任何数据类型（整数、字符串、浮点数、Python对象等）。每个元素都有一个标签（索引），可以通过标签访问数据。
- DataFrame: 二维标签化数据结构，类似于电子表格或SQL表格。它由行和列组成，每个列可以是不同的数据类型。

## Series
Series是一种类似于字典（dict-like）的一维数组（array-like）对象。它由两部分组成：数据（values）和索引（index）。
- 数据（values）是一个包含任意数据类型的数组（ndarray），而索引（index）是一个与数据对应的标签数组。
- Series的索引可以是整数、字符串或其他类型的标签。默认情况下，Series会自动生成整数索引（从0开始），但你也可以自定义索引。

In [122]:
# 字典可读性更高
user_info = {
    'name': '张三',
    'age': 18, 
    'address': '北京市'
}

In [123]:
user_info['name']

'张三'

In [124]:
user_info

{'name': '张三', 'age': 18, 'address': '北京市'}

### 构造series

In [125]:
import numpy as np
import pandas as pd

#### 使用ndarray构造Series 是一个引用对象

In [126]:
arr1 = np.random.randint(0, 10, size=5)
arr1

array([6, 9, 6, 6, 9])

In [127]:
arr1[0] = 100#修改arr1中的第一个元素的值为100,s1和arr1是引用对象，所以s1中的第一个元素的值也会被修改为100
arr1

array([100,   9,   6,   6,   9])

In [128]:
s1 = pd.Series(data = arr1)
s1

0    100
1      9
2      6
3      6
4      9
dtype: int64

In [129]:
# index是用来指定series对象的显示索引的标签，默认是0,1,2,3,4，如果我们想要指定成其他的标签，可以通过index参数来指定
s2 = pd.Series(data=arr1, index=['a', 'b', 'c', 'd', 'e'])
s2

a    100
b      9
c      6
d      6
e      9
dtype: int64

#### 使用列表构造Series 是一个副本对象

In [130]:
list("abcde")#将字符串"abcde"转换成列表['a', 'b', 'c', 'd', 'e']

['a', 'b', 'c', 'd', 'e']

In [131]:
list1 = [1, 2, 3, 4, 5]
s3 = pd.Series(data=list1,index=list("ABCDE"))
s3

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [132]:
list1[0] = 100#修改list1中的第一个元素的值为100,s3和list1是副本对象，所以s3中的第一个元素的值不会被修改为100
list1

[100, 2, 3, 4, 5]

In [133]:
s3

A    1
B    2
C    3
D    4
E    5
dtype: int64

#### 使用字典构造Series 是一个副本对象

In [134]:
dict1 = {"a": 1, "b": 2, "c": 3, "d": 4, "e": 5}
dict1

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

In [135]:
pd.Series(data=dict1)
#使用字典构造Series时，字典的键会被用作Series的索引，字典的值会被用作Series的数据，所以s4中的索引是'a','b','c','d','e'，数据是1,2,3,4,5

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [136]:
pd.Series(data=dict1, index = ['a', 'B', 'C', 'D', 'e'])
#使用字典构造Series时，如果指定了index参数，那么就会按照index参数指定的索引来构造Series，如果index参数中有某个索引在字典中没有对应的键，那么这个索引对应的数据就是NaN，所以s5中的索引是'A','B','C','D','E'，数据是NaN,NaN,NaN,NaN,NaN

a    1.0
B    NaN
C    NaN
D    NaN
e    5.0
dtype: float64

#### 使用scalar value构造Series 是一个副本对象

- 当使用标量值（scalar value）构造Series时，Series会将这个标量值复制到所有的元素中，因此每个元素都是这个标量值的副本对象，而不是引用对象。
- 使用一个标量（常量或者变量）构造Series时，必须指定index参数来定义Series的长度，否则会报错，因为Series不知道要创建多少个元素来存储这个标量值。

In [137]:
pd.Series(10,index = ['a', 'b', 'c', 'd', 'e'])

a    10
b    10
c    10
d    10
e    10
dtype: int64

### Series的属性

- name：返回Series对象的名称，可以是任何数据类型。
- shape：返回Series对象的形状，即数据的维度。
- index：返回Series对象的索引对象，可以是整数、字符串或其他类型的标签。
- values：返回Series对象的数据部分，即一个包含任意数据类型的数组（ndarray）。
- size：返回Series对象中元素的数量。

In [138]:
s1 = pd.Series(data=np.array([1, 2, 3, 4, 5]), index=['a', 'b', 'c', 'd', 'e'], name='kk')
s1

a    1
b    2
c    3
d    4
e    5
Name: kk, dtype: int64

In [139]:
pd.DataFrame(s1)

   kk
a   1
b   2
c   3
d   4
e   5

In [140]:
s1['a']#通过索引标签来访问Series对象中的数据

np.int64(1)

In [141]:
s1.a#通过属性访问的方式来访问Series对象中的数据，前提是索引标签必须是合法的Python标识符，否则会报错，比如s1['a']是合法的索引标签，可以通过s1.a来访问，但是如果索引标签是'a-b'，就不能通过属性访问的方式来访问，只能通过s1['a-b']来访问

np.int64(1)

In [142]:
s1.values#Series对象的values属性可以获取Series对象中的数据，返回一个numpy数组

array([1, 2, 3, 4, 5])

In [143]:
s1.shape#Series对象的shape属性可以获取Series对象的形状，返回一个元组，表示Series对象的维度

(5,)

In [144]:
s1.index#Series对象的index属性可以获取Series对象的索引，返回一个Index对象，表示Series对象的索引标签

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

In [145]:
s1.size#Series对象的size属性可以获取Series对象中元素的数量，返回一个整数，表示Series对象中元素的数量

5

### Series的数学运算

#### Series对大多数Numpy的数学运算都支持，并且会自动对齐索引。

#### 1）与非pandas对象进行运算时，Series会将非pandas对象广播到Series的索引上。

In [146]:
s1

a    1
b    2
c    3
d    4
e    5
Name: kk, dtype: int64

In [147]:
s1 + 1#Series对象的加法运算会对Series对象中的每个元素进行加法运算，返回一个新的Series对象，新的Series对象中的每个元素都是原来Series对象中的元素加上1的结果

a    2
b    3
c    4
d    5
e    6
Name: kk, dtype: int64

#### 2) Numpy functions对Series对象的运算会自动对齐索引，并且会返回一个新的Series对象，新的Series对象中的每个元素都是原来Series对象中的元素经过Numpy函数运算后的结果。

In [148]:
np.power(s1, 2)#Numpy函数对Series对象的运算会自动对齐索引，并且会返回一个新的Series对象，新的Series对象中的每个元素都是原来Series对象中的元素经过Numpy函数运算后的结果，比如np.power(s1, 2)会对s1中的每个元素进行平方运算，返回一个新的Series对象，新的Series对象中的每个元素都是原来Series对象中的元素的平方结果

a     1
b     4
c     9
d    16
e    25
Name: kk, dtype: int64

#### 3) Series对象之间进行运算时，会根据索引对齐进行运算，如果某个索引在其中一个Series中不存在，那么结果中该索引的值将会是NaN（Not a Number）。

In [149]:
s1

a    1
b    2
c    3
d    4
e    5
Name: kk, dtype: int64

In [150]:
s2 = pd.Series(data=np.array([10, 20, 30, 40, 50]), index=['b', 'a', 'c', 'd', 'f'])
s2

b    10
a    20
c    30
d    40
f    50
dtype: int64

In [151]:
s1 + s2

a    21.0
b    12.0
c    33.0
d    44.0
e     NaN
f     NaN
dtype: float64

In [152]:
s3 = pd.Series(data=np.array([100, 200, 300, 400]), index=['a', 'b', 'c', 'd'])
s3

a    100
b    200
c    300
d    400
dtype: int64

In [153]:
s1 + s3

a    101.0
b    202.0
c    303.0
d    404.0
e      NaN
dtype: float64

## DataFrame
DataFrame是一个二维标签化数据结构，类似于电子表格或SQL表格。它由行和列组成，每个列可以是不同的数据类型。   
DataFrame的每一列都是一个Series对象，因此DataFrame可以看作是由多个Series对象(共用同一个索引)组成的集合。   
DataFrame的行和列都有自己的索引，可以通过索引访问数据。   
- 行索引：index
- 列索引：columns
- 数据：values

In [154]:
list1 = [1, 2, "name"]

s1 = pd.Series(data=list1)

In [155]:
#Series和ndarray一样，会强制类型转换
s1.dtype#Series对象的dtype属性可以获取Series对象中元素的数据类型，返回一个数据类型对象，表示Series对象中元素的数据类型

dtype('O')

> dtype('O')表示Series对象中元素的数据类型是对象类型，也就是字符串类型，因为Series对象中的元素有一个是字符串"name"，所以整个Series对象的dtype就是对象类型。

### 构造DataFrame

pd.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)
- data：可以是一个二维数组、一个字典、一个Series对象或者一个DataFrame对象，用来构造DataFrame对象的数据。
- index：用来指定DataFrame对象的行索引标签，默认是0,1,2,...，如果我们想要指定成其他的标签，可以通过index参数来指定。
- columns：用来指定DataFrame对象的列索引标签，默认是0,1,2,...，如果我们想要指定成其他的标签，可以通过columns参数来指定。
- dtype：用来指定DataFrame对象中元素的数据类型，如果不指定，Pandas会根据数据的类型自动推断。
- copy：用来指定是否复制数据，默认为False，如果为True，则会复制数据，否则会直接使用原数据的引用。

In [156]:
#构造一个DataFrame对象，数据是一个3行3列的二维数组，行索引是'a','b','c'，列索引是'A','B','C'
pd.DataFrame(data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), index=['a', 'b', 'c'], columns=['A', 'B', 'C'])

   A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [157]:
data = np.random.randint(0, 100, size=(3, 4))
index = ['小张', '小李', '小王']
columns = ['语文', '数学', '英语', '体育']
pd.DataFrame(data=data, index=index, columns=columns)

    语文  数学  英语  体育
小张  21  88  65  16
小李  80  41  77  55
小王  34  68   2  67

#### 1）From dict of Series or dicts 使用一个由Series对象或者字典对象组成的字典来构造DataFrame对象，字典的键将成为DataFrame的列索引，字典的值将成为DataFrame的列数据。

In [158]:
names = pd.Series(data=['小张', '小李', '小王'])
yuwen = pd.Series(data=np.random.randint(0, 100, size=3))
math = pd.Series(data=np.random.randint(0, 100, size=3))
english = pd.Series(data=np.random.randint(0, 100, size=3))
dict1 = {
    '姓名': names,
    '语文': yuwen,
    '数学': math,
    '英语': english
}
pd.DataFrame(dict1)

   姓名  语文  数学  英语
0  小张  62  37   2
1  小李  30  45  51
2  小王  67  75  31

#### 2）From dict of ndarrays、lists、tuples 使用一个由ndarray对象、列表对象或者元组对象组成的字典来构造DataFrame对象，字典的键将成为DataFrame的列索引，字典的值将成为DataFrame的列数据。
ndarray对象、列表对象或者元组对象必须具有相同的长度，否则会报错。

In [159]:
dict1 = {
    '姓名': ['小张', '小李', '小王'],
    '语文': [80, 90, 85],
    '数学': [85, 95, 80],
    '英语': [90, 85, 88],
    '体育': [95, 80, 90]
}
pd.DataFrame(dict1)

   姓名  语文  数学  英语  体育
0  小张  80  85  90  95
1  小李  90  95  85  80
2  小王  85  80  88  90

#### 3）From a list of dicts 使用一个由字典对象组成的列表来构造DataFrame对象，列表中的每个字典对象将成为DataFrame对象的一行数据，字典的键将成为DataFrame的列索引，字典的值将成为DataFrame的列数据。

In [160]:
dict2 = {
    'name': '小明',
    '语文': 90,
    '数学': 85,
    '英语': 88,
    '体育': 90
}
list_of_dicts = [dict1, dict2]
display(list_of_dicts)
pd.DataFrame(list_of_dicts)

[{'姓名': ['小张', '小李', '小王'],
  '语文': [80, 90, 85],
  '数学': [85, 95, 80],
  '英语': [90, 85, 88],
  '体育': [95, 80, 90]},
 {'name': '小明', '语文': 90, '数学': 85, '英语': 88, '体育': 90}]

             姓名            语文            数学            英语            体育 name
0  [小张, 小李, 小王]  [80, 90, 85]  [85, 95, 80]  [90, 85, 88]  [95, 80, 90]  NaN
1           NaN            90            85            88            90   小明

#### 4）DataFrame.from_dict()方法可以从一个字典对象中创建一个DataFrame对象，字典的键将成为DataFrame的列索引，字典的值将成为DataFrame的列数据。

In [161]:
names = ['小张', '小李', '小王']
yuwen = np.random.randint(0, 100, size=3)
math = np.random.randint(0, 100, size=3)
english = np.random.randint(0, 100, size=3)
display(names, yuwen, math, english)

['小张', '小李', '小王']

array([35, 14, 11])

array([98, 52, 46])

array([70, 93,  7])

In [162]:
dict1 = {
    'name': ['小张', '小李', '小王'],
    '语文': yuwen,
    '数学': math,
    '英语': english
}
pd.DataFrame(data=dict1)

  name  语文  数学  英语
0   小张  35  98  70
1   小李  14  52  93
2   小王  11  46   7

## Pandas访问

In [163]:
arr1 = np.random.randint(0, 10, size=(3, 4))
arr1

array([[8, 9, 8, 6],
       [6, 0, 1, 4],
       [9, 8, 2, 9]])

In [164]:
df = pd.DataFrame(data=arr1,columns=list("ABCD"))
df

   A  B  C  D
0  8  9  8  6
1  6  0  1  4
2  9  8  2  9

In [165]:
df.values#DataFrame对象的values属性可以获取DataFrame对象中的数据，返回一个numpy数组

array([[8, 9, 8, 6],
       [6, 0, 1, 4],
       [9, 8, 2, 9]])

### Basics标准访问形式

> 显式访问：在pandas对象中，可以使用标签的形式访问数据，例如：df['A']可以访问DataFrame对象df中的列索引为'A'的列数据，df.loc[0]可以访问DataFrame对象df中的行索引为0的行数据。   
> 隐式访问：在pandas对象中，可以使用位置的形式访问数据，例如：df.iloc[0]可以访问DataFrame对象df中的第一行数据，df.iloc[:, 0]可以访问DataFrame对象df中的第一列数据。

In [166]:
df

   A  B  C  D
0  8  9  8  6
1  6  0  1  4
2  9  8  2  9

### 使用Labels访问（显式访问 loc[labels]）

s.loc[label]：使用标签访问Series对象中的数据，返回一个标量值。   
df.loc[row_label, col_label]：使用标签访问DataFrame对象中的数据，返回一个标量值。   

labels:标签名，标签名列表，bool列表（没有标签的列表（ndarray），有标签的列表（series）），切片  ,条件表达式

In [167]:
s1 = pd.Series(data=np.random.randint(1, 10, 5), index=['a', 'b', 'c', 'd', 'e'])
s1

a    8
b    5
c    1
d    6
e    8
dtype: int64

In [168]:
s1.loc['a']#使用标签访问Series对象中的数据，返回一个标量值

np.int64(8)

In [169]:
s1.loc[['a', 'b', 'c']]#使用标签访问Series对象中的数据，返回一个Series对象

a    8
b    5
c    1
dtype: int64

In [170]:
s1.loc['a':'c']#使用标签切片，返回一个Series对象，包含从索引标签'a'到索引标签'c'的所有元素，包括'a'和'c'

a    8
b    5
c    1
dtype: int64

In [171]:
s1.loc[[False, True, True, False, False]]#使用布尔列表访问Series对象中的数据，返回一个Series对象，包含索引标签对应的布尔值为True的元素

b    5
c    1
dtype: int64

In [172]:
s1 > 5#使用条件表达式访问Series对象中的数据，返回一个Series对象，包含索引标签对应的元素满足条件表达式的元素

a     True
b    False
c    False
d     True
e     True
dtype: bool

In [173]:
s1.loc[s1 > 5]#使用布尔表达式访问Series对象中的数据，返回一个Series对象，包含索引标签对应的布尔表达式为True的元素

a    8
d    6
e    8
dtype: int64

> 使用索引切片的都是左闭右开，使用标签进行切片的都是左闭右闭。

In [174]:
df

   A  B  C  D
0  8  9  8  6
1  6  0  1  4
2  9  8  2  9

df.loc[row_labels, col_labels]：使用标签访问DataFrame对象中的数据，返回一个DataFrame对象。

In [175]:
df.loc[0, 'A']#使用标签访问DataFrame对象中的数据，返回一个标量值

np.int64(8)

In [176]:
df.loc[0]#使用标签访问DataFrame对象中的数据，返回一个Series对象，包含第0行的数据

A    8
B    9
C    8
D    6
Name: 0, dtype: int64

In [177]:
df.loc[:, ['A', 'B']]#使用标签访问DataFrame对象中的数据，返回一个DataFrame对象，包含索引标签为'A'和'B'的列的所有数据

   A  B
0  8  9
1  6  0
2  9  8

In [178]:
df.loc[[0, 1], ['A', 'B']]#使用标签访问DataFrame对象中的数据，返回一个DataFrame对象，包含索引标签为0和1的行，以及索引标签为'A'和'B'的列的所有数据

   A  B
0  8  9
1  6  0

In [179]:
df.loc[[True, False, True]]#使用标签访问DataFrame对象中的数据，返回一个DataFrame对象，包含索引标签为True的行的数据

   A  B  C  D
0  8  9  8  6
2  9  8  2  9

In [180]:
bool_list = pd.Series(data = np.array([True, False, True]), index=[1, 0, 2])
bool_list

1     True
0    False
2     True
dtype: bool

In [181]:
#bool_list是一个Series对象，索引标签是1,0,2，数据是True,False,True，所以df.loc[bool_list]会返回一个DataFrame对象，包含索引标签为1和2的行的数据，因为索引标签为0的行对应的值是False，所以不会被包含在返回的DataFrame对象中
df.loc[bool_list]#使用标签访问DataFrame对象中的数据，返回一个DataFrame对象，包含索引标签为True的行的数据

   A  B  C  D
1  6  0  1  4
2  9  8  2  9

In [182]:
bool_list1 = pd.Series(data = np.array([True, False, True, False]), index=[1, 0, 2, 3])
bool_list1

1     True
0    False
2     True
3    False
dtype: bool

In [183]:
#如果直接使用bool——list1作为列索引来访问df，会由于索引对不上而报错，所以需要使用bool_list1.values来获取bool_list1中的数据，返回一个numpy数组，这样就可以正确地访问df中的列了
df.loc[:,bool_list1.values]

   A  C
0  8  8
1  6  1
2  9  2

### 使用index访问（隐式访问 iloc[index]）

s.iloc[index]：使用位置访问Series对象中的数据，返回一个标量值。   
df.iloc[row_index, col_index]：使用位置访问DataFrame对象中的数据，返回一个标量值。   
index:整数位置，整数位置列表，bool列表（没有标签的列表（ndarray），有标签的列表（series）），切片 (左闭右开) ,条件表达式

In [184]:
df

   A  B  C  D
0  8  9  8  6
1  6  0  1  4
2  9  8  2  9

In [185]:
df.iloc[0]#使用位置访问DataFrame对象中的数据，返回一个Series对象，包含第0行的数据

A    8
B    9
C    8
D    6
Name: 0, dtype: int64

In [186]:
df.iloc[:, 0]#使用位置访问DataFrame对象中的数据，返回一个Series对象，包含第0列的数据

0    8
1    6
2    9
Name: A, dtype: int64

In [187]:
df.iloc[[True, False, True]]#使用位置访问DataFrame对象中的数据，返回一个DataFrame对象，包含索引位置为True的行的数据

   A  B  C  D
0  8  9  8  6
2  9  8  2  9

In [188]:
df.iloc[0:2]#隐式访问，左闭右开

   A  B  C  D
0  8  9  8  6
1  6  0  1  4

In [189]:
df.loc[0:2]#显式访问，左闭右闭

   A  B  C  D
0  8  9  8  6
1  6  0  1  4
2  9  8  2  9

### 间接访问（坑）:不推荐

In [190]:
df

   A  B  C  D
0  8  9  8  6
1  6  0  1  4
2  9  8  2  9

In [191]:
df.loc[0].loc['A']#使用标签访问DataFrame对象中的数据，返回一个标量值

np.int64(8)

In [192]:
df.loc[0, 'A']#使用标签访问DataFrame对象中的数据，返回一个标量值

np.int64(8)

> 注意：直接用中括号访问，标签访问的是列，标签切片访问的是行

df可以看作是一个由series组成的字典，字典的键是列索引，字典的值是series对象。

In [193]:
df['A'] # 把DataFrame对象看作是一个由series组成的字典，字典的键是列索引，字典的值是series对象。

0    8
1    6
2    9
Name: A, dtype: int64

In [194]:
df[['A', 'B']] # 把DataFrame对象看作是一个由series组成的字典，字典的键是列索引，字典的值是series对象。

   A  B
0  8  9
1  6  0
2  9  8

In [195]:
df.loc[0:2]#显式访问，左闭右闭

   A  B  C  D
0  8  9  8  6
1  6  0  1  4
2  9  8  2  9

### where()and mask()方法
where()方法和mask()方法都是用于根据条件筛选数据的方法，它们的作用是相反的。
- where()方法：返回一个新的DataFrame对象，其中满足条件的元素保持不变，其他元素被替换为other参数指定的值。
- mask()方法：返回一个新的DataFrame对象，其中满足条件的元素被替换为other参数指定的值，其他元素保持不变。

In [228]:
df = pd.DataFrame(data=np.random.randint(0, 100, size=(5, 4)), columns=list("ABCD"))
df

    A   B   C   D
0  65   8  15  45
1  57   9  81  13
2  45  42  87  29
3  84  39  59  55
4  68  73  87  66

In [197]:
condition = df > 60

In [198]:
df.where(cond = condition,other ='不及格')

     A    B    C    D
0  不及格  不及格   69   71
1  不及格  不及格  不及格  不及格
2  不及格   63  不及格   79
3  不及格   89  不及格   88
4  不及格  不及格  不及格   62

In [199]:
df['B'] > 60

0    False
1    False
2     True
3     True
4    False
Name: B, dtype: bool

In [200]:
df.where(cond = df['B'] > 60)#只保留B列大于60的行，其他行被替换为NaN

      A     B     C     D
0   NaN   NaN   NaN   NaN
1   NaN   NaN   NaN   NaN
2  15.0  63.0  16.0  79.0
3   1.0  89.0  14.0  88.0
4   NaN   NaN   NaN   NaN

In [229]:
df.where(cond = df>60,other = pd.Series(data=[100,200],index = ['A','B']),axis=1)
#只保留df中大于60的元素，其他元素被替换为pd.Series(data=[100,200],index = ['A','B'])中的对应值，axis=1表示按列对齐，axis=0表示按行对齐

     A    B     C     D
0   65  200   NaN   NaN
1  100  200  81.0   NaN
2  100  200  87.0   NaN
3   84  200   NaN   NaN
4   68   73  87.0  66.0

In [202]:
df.where(cond = df > 60,other = pd.Series(data=[100,200],index = [0,1]),axis=0)

       A      B      C      D
0  100.0  100.0   69.0   71.0
1  200.0  200.0  200.0  200.0
2    NaN   63.0    NaN   79.0
3    NaN   89.0    NaN   88.0
4    NaN    NaN    NaN   62.0

In [203]:
df.mask(cond = df>60,other = '及格')

    A   B   C   D
0  48  29  及格  及格
1  39  56  44  42
2  15  及格  16  及格
3   1  及格  14  及格
4   2  14   7  及格

In [204]:
df.mask(cond = df>60,other = pd.Series(data=[100,200],index = ['A','B']),axis=1)

    A    B     C     D
0  48   29   NaN   NaN
1  39   56  44.0  42.0
2  15  200  16.0   NaN
3   1  200  14.0   NaN
4   2   14   7.0   NaN

### The query() Method

In [230]:
df.query('A > 20 and B > 60')#只保留A列大于20且B列大于60的行

    A   B   C   D
4  68  73  87  66

In [231]:
df.query('B > 60')

    A   B   C   D
4  68  73  87  66

### The filter() Method:对行名和列名进行筛选

In [232]:
df.columns = ['AA','BB','CB','DB']
df

   AA  BB  CB  DB
0  65   8  15  45
1  57   9  81  13
2  45  42  87  29
3  84  39  59  55
4  68  73  87  66

使用items选择行、列名称，配合axis参数可以选择行或者列，axis=0表示选择行，axis=1表示选择列。

In [233]:
df.filter(items=['AA','BB'],axis=1)#只保留列索引为'AA'和'BB'的列，axis=1表示按列对齐，axis=0表示按行对齐

   AA  BB
0  65   8
1  57   9
2  45  42
3  84  39
4  68  73

使用regex正则表达式，模糊匹配名称

In [234]:
df.filter(regex='B',axis=1)#只保留列索引中包含'B'的列，axis=1表示按列对齐，axis=0表示按行对齐

   BB  CB  DB
0   8  15  45
1   9  81  13
2  42  87  29
3  39  59  55
4  73  87  66

In [235]:
df.filter(regex='^B',axis=1)#只保留列索引中以'B'开头的列，axis=1表示按列对齐，axis=0表示按行对齐

   BB
0   8
1   9
2  42
3  39
4  73

## 聚合函数

pandas提供了许多内置的聚合函数，可以对DataFrame对象进行聚合操作。默认是列方向的聚合
- count()：计算非NA/null值的数量。
- sum()：计算数值列的总和。
- mean()：计算数值列的平均值。
- median()：计算数值列的中位数。
- min()：计算数值列的最小值。
- max()：计算数值列的最大值。
- std()：计算数值列的标准差。
- var()：计算数值列的方差。

In [236]:
df

   AA  BB  CB  DB
0  65   8  15  45
1  57   9  81  13
2  45  42  87  29
3  84  39  59  55
4  68  73  87  66

In [237]:
df.loc[1,'BB'] = np.nan#将df中索引为1，列索引为'BB'的元素的值修改为NaN

In [238]:
df

   AA    BB  CB  DB
0  65   8.0  15  45
1  57   NaN  81  13
2  45  42.0  87  29
3  84  39.0  59  55
4  68  73.0  87  66

In [239]:
df.sum(axis=1)#pandas对象自动忽略空值

0    133.0
1    151.0
2    203.0
3    237.0
4    294.0
dtype: float64

In [240]:
df.sum().sum()#先对列求和，再对行求和，得到整个DataFrame对象的总和

np.float64(1018.0)

# 习题

背景：假设班级有张三、李四、王五、赵六四个同学，考试要考的科目有Python、Java、C三门课程
- 1.假设score1是期中考试成绩，score2是期末考试成绩，请自由创建score1和score2两个DataFrame对象，并将其相加，求期中和期末的平均值。

In [216]:
score1 = pd.DataFrame(data=np.random.randint(0, 100, size=(4,3)), columns=['Python', 'Java', 'C'], index=['张三', '李四', '王五', '赵六'])
score2 = pd.DataFrame(data=np.random.randint(0, 100, size=(4,3)), columns=['Python', 'Java', 'C'], index=['张三', '李四', '王五', '赵六'])
display(score1, score2)

    Python  Java   C
张三      29    23  20
李四      17    40  69
王五      59    83  87
赵六      95    80  13

    Python  Java   C
张三      59     8  43
李四      74    99   7
王五      34    58  29
赵六      32    17  80

In [217]:
score1.mean(axis=1)#计算每一行的平均值，返回一个Series对象，索引是行索引，数据是每一行的平均值

张三    24.000000
李四    42.000000
王五    76.333333
赵六    62.666667
dtype: float64

In [218]:
score2.mean(axis=1)#计算每一行的平均值，返回一个Series对象，索引是行索引，数据是每一行的平均值

张三    36.666667
李四    60.000000
王五    40.333333
赵六    43.000000
dtype: float64

- 2.假设张三其中考试成绩java被发现有作弊行为，期中考试成绩被取消，请将张三的期中考试成绩置为0分

In [219]:
score1.loc['张三', 'Java'] = 0#将score1中索引为'张三'，列索引为'Java'的元素的值修改为0

In [220]:
score1

    Python  Java   C
张三      29     0  20
李四      17    40  69
王五      59    83  87
赵六      95    80  13

- 3.李四以为举报张三作弊有功，期中考试所有科目成绩加10分

In [221]:
score1.loc['李四'] += 10#将score1中索引为'李四'的行的所有元素的值加10

In [222]:
score1

    Python  Java   C
张三      29     0  20
李四      27    50  79
王五      59    83  87
赵六      95    80  13

- 4.由于有一道题出错，要给所有学生期末考试所有科目成绩加5分

In [223]:
score2 = score2 + 5
score2

    Python  Java   C
张三      64    13  48
李四      79   104  12
王五      39    63  34
赵六      37    22  85

- 5.Python老师想知道哪些学生的java成绩比Python成绩高，如何实现

In [224]:
cond = score2['Java'] > score2['Python']#创建一个布尔Series对象，索引是score2的行索引，数据是score2中每一行的'Java'列的值是否大于'Python'列的值

In [225]:
cond

张三    False
李四     True
王五     True
赵六    False
dtype: bool

In [226]:
score2.loc[cond]#使用布尔Series对象来访问DataFrame对象中的数据，返回一个DataFrame对象，包含索引标签对应的布尔Series对象为True的行的数据

    Python  Java   C
李四      79   104  12
王五      39    63  34

In [227]:
score2.loc[cond].index

Index(['李四', '王五'], dtype='str')

## 单层索引和多层级索引

In [241]:
import numpy as np
import pandas as pd

In [252]:
df = pd.DataFrame(data=np.random.randint(0, 100, size=(5, 3)),columns=list("ABC"))
df

    A   B   C
0   5  22  51
1  19  17  18
2  35  63  30
3  66  85   8
4  43  44  82

In [254]:
df.index = ['a', 'b', 'c', 'd', 'e']

In [255]:
df

    A   B   C
a   5  22  51
b  19  17  18
c  35  63  30
d  66  85   8
e  43  44  82

In [256]:
df.columns = ['AA', 'BB', 'CC']

In [257]:
df

   AA  BB  CC
a   5  22  51
b  19  17  18
c  35  63  30
d  66  85   8
e  43  44  82

### 单层索引

- pd.Index是pandas中用于表示索引的类，它可以是整数、字符串或者其他类型的标签。单层索引是指索引只有一层，即每个标签都是唯一的，没有嵌套结构。

pd.Index(data=None, dtype=None, copy=False, name=None, tupleize_cols=True, **kwargs)
- data：可以是一个一维数组、一个列表、一个元组或者一个Series

In [258]:
pd.Index(data = list('absde'))#创建一个Index对象，索引标签是'a','b','c','d','e'

Index(['a', 'b', 's', 'd', 'e'], dtype='str')

- pd.RangeIndex是pandas中用于表示整数范围索引的类，它是pd.Index的一个子类。RangeIndex表示一个连续的整数范围，可以通过start、stop和step参数来定义。

pd.RangeIndex(start=0, stop=None, step=1, dtype=None, copy=False)
- start：表示索引的起始值，默认为0。
- stop：表示索引的结束值，必须指定。
- step：表示索引的步长，默认为1。

In [262]:
m_index  = pd.RangeIndex(start=0, stop=5, step=1,name='index')#创建一个RangeIndex对象，索引标签是0,1,2,3,4

In [263]:
df.index = m_index

In [264]:
df

       AA  BB  CC
index
0       5  22  51
1      19  17  18
2      35  63  30
3      66  85   8
4      43  44  82

pd.CategoricalIndex是pandas中用于表示分类变量索引的类，它是pd.Index的一个子类。CategoricalIndex表示一个有限的、离散的类别集合，可以通过categories参数来定义。

pd.CategoricalIndex(data=None, categories=None, ordered=False, dtype=None, copy=False, name=None)
- data：可以是一个一维数组、一个列表、一个元组或者一个Series对象，用来构造CategoricalIndex对象的数据。
- categories：用来指定CategoricalIndex对象的类别集合，必须是一个一维数组、一个列表或者一个元组，且不能包含重复的元素。
- ordered：用来指定CategoricalIndex对象的类别是否有序，默认为False，表示类别是无序的。如果为True，则表示类别是有序的。
- dtype：用来指定CategoricalIndex对象中元素的数据类型，如果不指定，Pandas会根据数据的类型自动推断。
- copy：用来指定是否复制数据，默认为False，如果为True，则会复制数据，否则会直接使用原数据的引用。
- name：用来指定CategoricalIndex对象的名称，可以是任何数据类型。

In [266]:
pd.CategoricalIndex(data=['a', 'b', 'c', 'd', 'e'])

CategoricalIndex(['a', 'b', 'c', 'd', 'e'], categories=['a', 'b', 'c', 'd', 'e'], ordered=False, dtype='category')

怎么使用索引：
- pd.Index是pandas提供的专门用于构造索引的类，它有很多子类，例如：pd.RangeIndex、pd.CategoricalIndex等。
- 所有的索引类都继承自pd.Index类，因此它们都具有pd.Index类的属性和方法。比如：可以使用索引访问元素
- 通常如果需要对索引进行定制（name），可以使用pd.Index系列方法来构造索引
- 如果没有特殊要求，建议使用默认的整数索引，因为它们更简单、更高效，并且可以避免一些潜在的问题。

### 多层级索引构造

pd.MultiIndex.from_product(iterables, sortorder=None, names=None)
- iterables：一个可迭代对象的列表，每个可迭代对象表示一个索引级别的标签集合，MultiIndex将会生成这些标签的笛卡尔积作为多层级索引的标签。
- names：一个列表，用于指定每个级别的索引名称，列表的长度必须与iterables的长度相同。如果为None，则表示不指定索引名称。

In [268]:
level1 = ['第一期','第二期']
level2 = ['A','B','C']

In [269]:
columns = pd.MultiIndex.from_product([level1, level2], names=['期数', '产品'])

In [273]:
index = pd.Index(['luck', 'tom', 'jerry'], name='姓名')

In [274]:
data = np.random.randint(0, 100, size=(3, 6))

In [275]:
df = pd.DataFrame(data=data, index=index, columns=columns)
df

期数    第一期         第二期
产品      A   B   C   A   B   C
姓名
luck   74  78   8   5  39  34
tom    47  39  81  24   2   8
jerry   9  14  34  84  65  74

In [294]:
index = pd.MultiIndex.from_product([['第一期','第二期'], ['luck', 'tom', 'jerry']])
index

MultiIndex([('第一期',  'luck'),
            ('第一期',   'tom'),
            ('第一期', 'jerry'),
            ('第二期',  'luck'),
            ('第二期',   'tom'),
            ('第二期', 'jerry')],
           )

In [291]:
columns = pd.Index(['A', 'B', 'C'])

In [292]:
data = np.random.randint(0, 100, size=(6, 3))

In [293]:
df = pd.DataFrame(data=data, index=index, columns=columns)
df

            A   B   C
第一期 luck   48  20  85
    tom    29  91   6
    jerry  99  22  87
第二期 luck   97  48  26
    tom    59  87  86
    jerry  87  60  85

- 使用pd.MultiIndex.from_tuples()方法可以从一个由元组组成的列表中创建一个MultiIndex对象，每个元组表示一个索引级别的标签集合，MultiIndex将会生成这些标签的笛卡尔积作为多层级索引的标签。

In [300]:
tuples = [('第一期', 'luck'), ('第一期', 'tom'), ('第一期', 'jerry'), ('第二期', 'luck'), ('第二期', 'tom'), ('第二期', 'jerry')]
columns = pd.MultiIndex.from_tuples(tuples)
columns

MultiIndex([('第一期',  'luck'),
            ('第一期',   'tom'),
            ('第一期', 'jerry'),
            ('第二期',  'luck'),
            ('第二期',   'tom'),
            ('第二期', 'jerry')],
           )

In [301]:
index = ['A', 'B', 'C']

In [302]:
data = np.random.randint(0, 100, size=(3, 6))

In [303]:
df = pd.DataFrame(data=data, index=index, columns=columns)

In [304]:
df

   第一期            第二期
  luck tom jerry luck tom jerry
A   47  49    25    0  56    76
B    5  43    64   62  29    87
C   99  81    26   71  39    32

### 多层索引的访问

In [305]:
df

   第一期            第二期
  luck tom jerry luck tom jerry
A   47  49    25    0  56    76
B    5  43    64   62  29    87
C   99  81    26   71  39    32

In [306]:
df.loc['A']

第一期  luck     47
     tom      49
     jerry    25
第二期  luck      0
     tom      56
     jerry    76
Name: A, dtype: int64

In [307]:
df.loc[['A', 'B']]

   第一期            第二期
  luck tom jerry luck tom jerry
A   47  49    25    0  56    76
B    5  43    64   62  29    87

In [308]:
df.loc['A' : 'B']

   第一期            第二期
  luck tom jerry luck tom jerry
A   47  49    25    0  56    76
B    5  43    64   62  29    87

In [327]:
df.columns

MultiIndex([('第一期', 'jerry'),
            ('第一期',  'luck'),
            ('第一期',   'tom'),
            ('第二期', 'jerry'),
            ('第二期',  'luck'),
            ('第二期',   'tom')],
           )

In [328]:
df.loc[:,('第一期', 'luck')]

A    47
B     5
C    99
Name: (第一期, luck), dtype: int64

In [329]:
df.loc[:,[('第一期', 'luck'), ('第二期', 'tom')]]

   第一期 第二期
  luck tom
A   47  56
B    5  29
C   99  39

In [331]:
#使用切片访问，将('第一期',  'luck')和('第二期', 'tom')之间的所有列都访问到
df = df.sort_index(axis=1)#多级列索引最好已经排序，否则可能报错或结果不符合预期
df.loc[:, ('第一期', 'luck') : ('第二期', 'tom')]

   第一期       第二期
  luck tom jerry luck tom
A   47  49    76    0  56
B    5  43    87   62  29
C   99  81    32   71  39

总结：
多层索引的访问逻辑与单层索引的访问逻辑类似，只是需要指定每个级别的标签或者位置。
但是多层索引的索引表达式形式是以元组的方式处理的

- 注意：使用切片，索引必须是排序的，否则可能报错或者结果不符合预期

In [333]:
# 隐式访问
df.iloc[:, 0:2]

    第一期
  jerry luck
A    25   47
B    64    5
C    26   99

In [334]:
df.iloc[0:2]

    第一期            第二期
  jerry luck tom jerry luck tom
A    25   47  49    76    0  56
B    64    5  43    87   62  29

### Stack 和 Unstack

stack()方法和unstack()方法是用于在DataFrame对象中进行行列转换的方法，它们的作用是相反的。
- stack()方法：将DataFrame对象的列索引转换为行索引，将DataFrame对象从宽格式转换为长格式。
- unstack()方法：将DataFrame对象的行索引转换为列索引，将DataFrame对象从长格式转换为宽格式。
参数说明：
- level：指定要堆叠或展开的索引级别，默认是最后一个级别（-1），从里到外数，-1表示最内层，-2表示次内层，以此类推。也可以使用正整数，从外到里数，0表示最外层，1表示次外层，以此类推。

In [341]:
df

    第一期            第二期
  jerry luck tom jerry luck tom
A    25   47  49    76    0  56
B    64    5  43    87   62  29
C    26   99  81    32   71  39

In [342]:
df.stack(level= -2)#将DataFrame对象的列索引转换为行索引，将DataFrame对象从宽格式转换为长格式

       jerry  luck  tom
A 第一期     25    47   49
  第二期     76     0   56
B 第一期     64     5   43
  第二期     87    62   29
C 第一期     26    99   81
  第二期     32    71   39

# 习题

#### 1.创建一个DataFrame对象，表示出lucy，tom，jack期中期末各科成绩

In [357]:
columns =  ['语文', '数学', '英语']

In [358]:
index = pd.Index(['lucy', 'tom', 'jack'])

In [373]:
data1 = np.random.randint(0, 100, size=(3, 3))
data2 = np.random.randint(0, 100, size=(3, 3))

In [375]:
df1 = pd.DataFrame(data=data1, index=index, columns=columns)
df2 = pd.DataFrame(data=data2, index=index, columns=columns)

In [376]:
display(df1, df2)

      语文  数学  英语
lucy  52  42  41
tom   30  11  87
jack  34  81  97

      语文  数学  英语
lucy  48  20  57
tom   28  25  34
jack  53  17   1

2.获取lucy的期末成绩的最高分科目

In [377]:
df1.loc['lucy']

语文    52
数学    42
英语    41
Name: lucy, dtype: int64

In [378]:
df1.loc['lucy'].max()

np.int64(52)

In [379]:
df1.loc['lucy'] == df1.loc['lucy'].max()

语文     True
数学    False
英语    False
Name: lucy, dtype: bool

In [382]:
df1.loc['lucy', df1.loc['lucy'] == df1.loc['lucy'].max()].index[0]

'语文'

In [385]:
#使用query方法来查询df1中lucy的最高分科目
df1

      语文  数学  英语
lucy  52  42  41
tom   30  11  87
jack  34  81  97

In [388]:
df1.T

    lucy  tom  jack
语文    52   30    34
数学    42   11    81
英语    41   87    97

In [391]:
df1.T.query('lucy == 52')

    lucy  tom  jack
语文    52   30    34

In [396]:
df1.T.query('lucy == 52').index[0]

'语文'

3.同时获取上学期和下学期tom的成绩，计算tom的各学科的平均成绩

In [397]:
columns = pd.MultiIndex.from_product([['上学期', '下学期'], ['语文', '数学', '英语']])

In [398]:
index

Index(['lucy', 'tom', 'jack'], dtype='str')

In [399]:
data = np.random.randint(0, 100, size=(3, 6))

In [400]:
df = pd.DataFrame(data=data, index=index, columns=columns)
df

     上学期         下学期
      语文  数学  英语  语文  数学  英语
lucy  64  74  79  88  75  25
tom   51  83  13  92  68  97
jack  74  43  62  27  65  75

In [404]:
tom_score = df.loc['tom']

In [405]:
tom_score

上学期  语文    51
     数学    83
     英语    13
下学期  语文    92
     数学    68
     英语    97
Name: tom, dtype: int64

In [407]:
tom_score.unstack(level=-1)

     数学  英语  语文
上学期  83  13  51
下学期  68  97  92

In [409]:
tom_score.unstack(level=-1).mean(axis=0)

数学    75.5
英语    55.0
语文    71.5
dtype: float64

4.获取上学期jack的数学成绩，并给他加20

In [410]:
df

     上学期         下学期
      语文  数学  英语  语文  数学  英语
lucy  64  74  79  88  75  25
tom   51  83  13  92  68  97
jack  74  43  62  27  65  75

In [411]:
df.iloc[2, 1] += 20#将df中索引为2，列索引为1的元素的值加20

In [412]:
df

     上学期         下学期
      语文  数学  英语  语文  数学  英语
lucy  64  74  79  88  75  25
tom   51  83  13  92  68  97
jack  74  63  62  27  65  75