# Panda数据处理

In [38]:
import numpy as np
import pandas as pd

## 数据IO操作

### pandas IO操作主要是读取和写入数据，pandas支持多种数据格式的读写操作，包括CSV、Excel、SQL、JSON等。

In [2]:
# 读取 CSV 文件
df = pd.read_csv('csv文件.csv')
df

   姓名  年龄  城市
0  张三  28  北京
1  李四  31  上海
2  王五  25  广州

In [ ]:
pd.read_csv("csv文件.csv", header=None)# header=None表示不将第一行作为列名，而是将其作为数据的一部分。

    0   1   2
0  姓名  年龄  城市
1  张三  28  北京
2  李四  31  上海
3  王五  25  广州

In [8]:
pd.read_csv("csv文件.csv", index_col="姓名")# index_col="姓名"表示将"姓名"列作为索引列。

    年龄  城市
姓名
张三  28  北京
李四  31  上海
王五  25  广州

#### pd.read_table()函数：读取以制表符（\t）分隔的文本文件，返回一个DataFrame对象。

In [23]:
df = pd.read_table("txt文件.txt", sep="\t", header=None)# sep="\t"表示以制表符（\t）作为分隔符。

In [ ]:
df #因为 read_table()函数默认以制表符（\t）作为分隔符，所以可以直接使用read_table()函数读取制表符分隔的文本文件。但是，如果文本文件使用其他分隔符（如逗号、空格等），则需要使用read_csv()函数，并指定sep参数为相应的分隔符。

          0
0  张三 28 北京
1  李四 31 上海
2  王五 25 广州

In [26]:
df = pd.read_table("txt文件.txt", sep=" ", header=None, index_col=0)# index_col=0表示将第一列作为索引列。
df

     1   2
0
张三  28  北京
李四  31  上海
王五  25  广州

In [27]:
# 使用read_csv()函数读取制表符分隔的文本文件
df = pd.read_csv("txt文件.txt", sep=" ", header=None)

In [28]:
df

    0   1   2
0  张三  28  北京
1  李四  31  上海
2  王五  25  广州

In [30]:
pd.read_csv("csv文件 copy.csv", sep="-")

   姓名  年龄  城市
0  张三  28  北京
1  李四  31  上海
2  王五  25  广州

In [35]:
pd.read_csv("csv文件 copy 2.csv", sep="\\s+")# sep="\\s+"表示以一个或多个空格作为分隔符。

   姓名  年龄  城市
0  张三  28  北京
1  李四  31  上海
2  王五  25  广州

### excel读取

In [42]:
data1 =  pd.read_excel('excel文件.xlsx')# 读取 Excel 文件,默认读取第一个工作表。
data1

   编号   名称  数值
0   1  数据1  10
1   2  数据2  20
2   3  数据3  30
3   4  数据4  40
4   5  数据5  50

In [43]:
data2 = pd.read_excel('excel文件.xlsx', sheet_name='Sheet2')# 读取 Excel 文件的指定工作表。
data2

   编号   名称  数值
0   1  项目1  15
1   2  项目2  25
2   3  项目3  35
3   4  项目4  45
4   5  项目5  55

In [44]:
data1.to_excel('output.xlsx', index=False)# 将 DataFrame 保存为 Excel 文件，index=False表示不保存索引列。

In [45]:
data1.to_csv('output.csv', index=False)# 将 DataFrame 保存为 CSV 文件，index=False表示不保存索引列。

## 数据探索

- describe()函数：用于快速查看数据的统计信息，包括计数、均值、标准差、最小值、最大值等。
- info()函数：用于查看数据的基本信息，包括数据类型、非空值数量、内存占用等。
- tail()函数：用于查看数据的最后几行，默认显示最后5行。
- sample()函数：用于随机抽样数据，可以指定抽样的数量或比例。

In [50]:
df = pd.DataFrame(data=np.random.randint(1, 10000, size=(1000, 5)), columns=['A', 'B', 'C', 'D', 'E'])# 创建一个包含1000行、5列的随机整数数据的DataFrame，整数范围为1到9999。
df

        A     B     C     D     E
0    3388   587  5388   531  2601
1    9638  5002  3786  4384  5979
2    3444  7034  5083  7677  1757
3    6362  4484  9927  8483  1289
4    8275  8167  2230  5714  4522
..    ...   ...   ...   ...   ...
995  6227  2103  7925  7217  1037
996   558  1027  3262  7737  7603
997   727  9518  2205  3708  3670
998  4095  7264  9800  8666  6442
999  1450  8085  7850  1315  3156

[1000 rows x 5 columns]

In [57]:
df.describe(percentiles=[.25, .5, .75, .99])# describe()函数用于快速查看数据的统计信息，包括计数、均值、标准差、最小值、最大值等。percentiles参数用于指定要计算的分位数。

               A            B            C            D            E
count  1000.0000  1000.000000  1000.000000  1000.000000  1000.000000
mean   5081.8350  5069.774000  5020.657000  4909.534000  4818.865000
std    2886.3104  2898.927323  2906.331345  2910.178003  2835.436508
min       8.0000    15.000000    30.000000     2.000000     4.000000
25%    2621.7500  2547.250000  2433.000000  2467.500000  2407.750000
50%    5037.0000  5105.000000  4925.500000  4763.500000  4795.000000
75%    7593.2500  7520.250000  7592.250000  7464.250000  7099.750000
99%    9878.1500  9905.080000  9914.040000  9879.090000  9859.200000
max    9996.0000  9992.000000  9992.000000  9998.000000  9992.000000

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       1000 non-null   int64
 1   B       1000 non-null   int64
 2   C       1000 non-null   int64
 3   D       1000 non-null   int64
 4   E       1000 non-null   int64
dtypes: int64(5)
memory usage: 39.2 KB

In [53]:
df.head()# head()函数用于查看数据的前几行，默认显示前5行。

      A     B     C     D     E
0  3388   587  5388   531  2601
1  9638  5002  3786  4384  5979
2  3444  7034  5083  7677  1757
3  6362  4484  9927  8483  1289
4  8275  8167  2230  5714  4522

In [55]:
df.tail(n = 10)# tail()函数用于查看数据的最后几行，n参数指定显示的行数，默认显示最后5行。

        A     B     C     D     E
990  2538  3341   312  8979  2271
991  1935  9607  8119  7367  4607
992  7148  7402  3809  9182  1159
993  1744  9979  7797   547  6695
994  8514  1308  7537  2189  9511
995  6227  2103  7925  7217  1037
996   558  1027  3262  7737  7603
997   727  9518  2205  3708  3670
998  4095  7264  9800  8666  6442
999  1450  8085  7850  1315  3156

In [56]:
df.sample(n=5)# sample()函数用于随机抽样数据，n参数指定抽样的数量。

        A     B     C     D     E
914  6450  7035  3542  2246   441
632  5756   418  9809  9503  3142
878  8197  6345  4537  6058  6205
746  2151  8001  9992  4666  4857
101  2223  1635  7975  5491   626

## 空值处理

### None

- None是Python中的一个特殊对象，表示空值。其类型为python object。因此，None不能参与到数值计算中，也不能与其他类型进行比较操作。
- object类型的运算要比数值类型的运算慢很多，因此在数据分析中，尽量避免使用object类型的数据。

In [58]:
type(None)

NoneType

## np.nan(NaN)

- np.nan是NumPy库中的一个特殊浮点数，表示“不是一个数字”（Not a Number）。它通常用于表示缺失或无效的数值数据。与None不同，np.nan是一个浮点数类型，可以参与数值计算，但在计算中会被视为缺失值(NaN)。
- 在numpy和pandas中，可以使用np.nanxxx()函数来处理NaN值，此时视nan为0。
- 因为np.nan是一个浮点数类型，所以在数据分析中，尽量使用np.nan来表示缺失值，而不是None。

In [60]:
type(np.nan)

float

In [61]:
def getsum(x):
    return x.sum()

In [62]:
data1 = np.arange(1, 10000001, dtype=object)

In [63]:
%timeit getsum(data1)

78.1 ms ± 952 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [64]:
data2 = np.arange(1, 10000001, dtype=np.float64)

In [66]:
%timeit getsum(data2)

1.14 ms ± 6.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

### pandas自动把None转换为np.nan

In [70]:
df = pd.DataFrame(data=np.random.randint(0, 10, size=(3, 5)), columns=['A', 'B', 'C', 'D', 'E'])# 创建一个包含100行5列的随机数DataFrame，列名为'A'、'B'、'C'、'D'和'E'。

In [71]:
df

   A  B  C  D  E
0  5  5  3  9  0
1  6  6  9  8  7
2  9  8  1  9  6

In [72]:
df.loc[2] = None# loc[]函数用于根据标签选择数据，df.loc[2]表示选择索引为2的行。将其赋值为None表示将该行的所有列的值都设置为缺失值。

In [73]:
df

     A    B    C    D    E
0  5.0  5.0  3.0  9.0  0.0
1  6.0  6.0  9.0  8.0  7.0
2  NaN  NaN  NaN  NaN  NaN

> NaN 是一个符号，表示“不是一个数字”（Not a Number），不是一个具体的数值。   
> 在pandas中，None和np.nan 都会被显示为缺失值(NaN).

### 空值查找

- isnull()函数：用于判断数据是否为缺失值(NaN)，返回一个布尔型的DataFrame或Series对象，缺失值为True，非缺失值为False。
- notnull()函数：用于判断数据是否为非缺失值，返回一个布尔型的DataFrame或Series对象，非缺失值为True，缺失值为False。

In [74]:
df

     A    B    C    D    E
0  5.0  5.0  3.0  9.0  0.0
1  6.0  6.0  9.0  8.0  7.0
2  NaN  NaN  NaN  NaN  NaN

In [86]:
df.isnull()# isnull()函数用于判断数据是否为缺失值(NaN)，返回一个布尔型的DataFrame或Series对象，缺失值为True，非缺失值为False。

       A      B      C      D      E
0  False  False  False  False  False
1  False  False  False  False  False
2   True   True   True   True   True

- any()函数：用于检查DataFrame或Series中是否存在任何True值。如果存在至少一个True值，返回True；否则返回False。默认情况下，any()函数沿着列方向（axis=0）进行操作，即检查每一列是否存在True值。如果希望沿着行方向（axis=1）进行操作，可以通过设置参数axis=1来实现。
- all()函数：用于检查DataFrame或Series中是否所有值都为True。如果所有值都为True，返回True；否则返回False。默认情况下，all()函数沿着列方向（axis=0）进行操作，即检查每一列是否所有值都为True。如果希望沿着行方向（axis=1）进行操作，可以通过设置参数axis=1来实现。

In [87]:
df.isnull().any()# any()函数用于检查DataFrame或Series中是否存在任何True值。如果存在至少一个True值，返回True；否则返回False。默认情况下，any()函数沿着列方向（axis=0）进行操作，即检查每一列是否存在True值。

A    True
B    True
C    True
D    True
E    True
dtype: bool

In [88]:
df.isnull().any(axis=1)# all()函数用于检查DataFrame或Series中是否所有值都为True。如果所有值都为True，返回True；否则返回False。默认情况下，all()函数沿着列方向（axis=0）进行操作，即检查每一列是否所有值都为True。如果希望沿着行方向（axis=1）进行操作，可以通过设置参数axis=1来实现。

0    False
1    False
2     True
dtype: bool

In [89]:
# 找出至少包含一个缺失值的行
df[df.isnull().any(axis=1)]# df.isnull().any(axis=1)返回一个布尔型的Series对象，表示每一行是否包含至少一个缺失值。然后使用布尔索引df[...]选择出包含至少一个缺失值的行

    A   B   C   D   E
2 NaN NaN NaN NaN NaN

In [90]:
# 找出至少包含一个缺失值的列
df.loc[:, df.isnull().any()]# df.isnull().any()返回一个布尔型的Series对象，表示每一列是否包含至少一个缺失值。然后使用布尔索引df.loc[:, ...]选择出包含至少一个缺失值的列

     A    B    C    D    E
0  5.0  5.0  3.0  9.0  0.0
1  6.0  6.0  9.0  8.0  7.0
2  NaN  NaN  NaN  NaN  NaN

In [91]:
df.notnull()# notnull()函数用于判断数据是否为非缺失值，返回一个布尔型的DataFrame或Series对象，非缺失值为True，缺失值为False。

       A      B      C      D      E
0   True   True   True   True   True
1   True   True   True   True   True
2  False  False  False  False  False

In [93]:
df.notnull().all(axis=1)# all()函数用于检查DataFrame或Series中是否所有值都为True。如果所有值都为True，返回True；否则返回False。默认情况下，all()函数沿着列方向（axis=0）进行操作，即检查每一列是否所有值都为True。

0     True
1     True
2    False
dtype: bool

In [94]:
# 取出所有非缺失值的行
df[df.notnull().all(axis=1)]# df.notnull().all(axis=1)返回一个布尔型的Series对象，表示每一行是否所有值都为非缺失值。然后使用布尔索引df[...]选择出所有非缺失值的行

     A    B    C    D    E
0  5.0  5.0  3.0  9.0  0.0
1  6.0  6.0  9.0  8.0  7.0

In [99]:
# 查看某一列的空值占比
df.isnull().mean()# isnull()函数用于判断数据是否为缺失值(NaN)，返回一个布尔型的DataFrame或Series对象，缺失值为True，非缺失值为False。mean()函数用于计算每一列的平均值，即空值占比。

A    0.333333
B    0.333333
C    0.333333
D    0.333333
E    0.333333
dtype: float64

> 列字段是不能轻易删除的

### 空值填充

fillna()函数：用于填充缺失值(NaN)，可以指定填充值或使用前一个/后一个有效值进行填充。

In [100]:
df

     A    B    C    D    E
0  5.0  5.0  3.0  9.0  0.0
1  6.0  6.0  9.0  8.0  7.0
2  NaN  NaN  NaN  NaN  NaN

In [101]:
df.fillna(value=0)# fillna()函数用于填充缺失值(NaN)，可以指定填充值或使用前一个/后一个有效值进行填充。

     A    B    C    D    E
0  5.0  5.0  3.0  9.0  0.0
1  6.0  6.0  9.0  8.0  7.0
2  0.0  0.0  0.0  0.0  0.0

In [103]:
df.mean()# mean()函数用于计算每一列的均值，返回一个包含每一列均值的Series对象。

A    5.5
B    5.5
C    6.0
D    8.5
E    3.5
dtype: float64

In [105]:
# 使用均值来填充缺失值
df.fillna(value=df.mean())# df.mean()计算每一列的均值，然后使用fillna()函数将缺失值填充为对应列的均值。

     A    B    C    D    E
0  5.0  5.0  3.0  9.0  0.0
1  6.0  6.0  9.0  8.0  7.0
2  5.5  5.5  6.0  8.5  3.5

In [106]:
df = pd.DataFrame(data=np.random.randint(0, 100, size=(10,3)), columns=['A', 'B', 'C'])# 创建一个包含10行3列的随机整数数据的DataFrame，整数范围为0到99。

In [107]:
df

    A   B   C
0  81  71  79
1  94  85  52
2  26  72  42
3  72  21  85
4  95  24  48
5  39  78   9
6  30  11  80
7  55  71   8
8  91  29  96
9  23  47   9

In [108]:
df.loc[3, 'B'] = None# loc[]函数用于根据标签选择数据，df.loc[3, 'B']表示选择索引为3的行和列名为'B'的列。将其赋值为None表示将该单元格的值设置为缺失值。
df.loc[5, 'C'] = None# loc[]函数用于根据标签选择数据，df.loc[5, 'C']表示选择索引为5的行和列名为'C'的列。将其赋值为None表示将该单元格的值设置为缺失值。
df.loc[9] = None# loc[]函数用于根据标签选择数据，df.loc[9]表示选择索引为9的行。将其赋值为None表示将该行的所有列的值都设置为缺失值。

In [109]:
df

      A     B     C
0  81.0  71.0  79.0
1  94.0  85.0  52.0
2  26.0  72.0  42.0
3  72.0   NaN  85.0
4  95.0  24.0  48.0
5  39.0  78.0   NaN
6  30.0  11.0  80.0
7  55.0  71.0   8.0
8  91.0  29.0  96.0
9   NaN   NaN   NaN

In [111]:
df.mean(axis=1)# mean()函数用于计算每一列的均值，返回一个包含每一列均值的Series对象。

0    77.000000
1    77.000000
2    46.666667
3    78.500000
4    55.666667
5    58.500000
6    40.333333
7    44.666667
8    72.000000
9          NaN
dtype: float64

In [113]:
df.fillna(value=df.mean(axis=1), axis=1)# fillna()函数用于填充缺失值(NaN)，可以指定填充值或使用前一个/后一个有效值进行填充。value=df.mean(axis=1)表示使用每一行的均值来填充缺失值，axis=0表示沿着列方向进行填充。

      A     B     C
0  81.0  71.0  79.0
1  94.0  85.0  52.0
2  26.0  72.0  42.0
3  72.0  78.5  85.0
4  95.0  24.0  48.0
5  39.0  78.0  58.5
6  30.0  11.0  80.0
7  55.0  71.0   8.0
8  91.0  29.0  96.0
9   NaN   NaN   NaN

In [117]:
# 使用临近值填充
df.ffill(axis=1)# ffill()函数用于使用前一个有效值来填充缺失值(NaN)，axis=1表示沿着行方向进行填充，即使用每一行的前一个有效值来填充缺失值。

      A     B     C
0  81.0  71.0  79.0
1  94.0  85.0  52.0
2  26.0  72.0  42.0
3  72.0  72.0  85.0
4  95.0  24.0  48.0
5  39.0  78.0  78.0
6  30.0  11.0  80.0
7  55.0  71.0   8.0
8  91.0  29.0  96.0
9   NaN   NaN   NaN

In [121]:
# 向后填充
df.bfill(axis=0)# bfill()函数用于使用后一个有效值来填充缺失值(NaN)，axis=1表示沿着行方向进行填充，即使用每一行的后一个有效值来填充缺失值。

      A     B     C
0  81.0  71.0  79.0
1  94.0  85.0  52.0
2  26.0  72.0  42.0
3  72.0  24.0  85.0
4  95.0  24.0  48.0
5  39.0  78.0  80.0
6  30.0  11.0  80.0
7  55.0  71.0   8.0
8  91.0  29.0  96.0
9   NaN   NaN   NaN

In [122]:
df

      A     B     C
0  81.0  71.0  79.0
1  94.0  85.0  52.0
2  26.0  72.0  42.0
3  72.0   NaN  85.0
4  95.0  24.0  48.0
5  39.0  78.0   NaN
6  30.0  11.0  80.0
7  55.0  71.0   8.0
8  91.0  29.0  96.0
9   NaN   NaN   NaN

### 空值过滤

dropna()函数：用于删除缺失值(NaN)所在的行或列。可以通过设置参数axis=0或axis=1来指定删除行或列，默认情况下删除行。

In [123]:
df

      A     B     C
0  81.0  71.0  79.0
1  94.0  85.0  52.0
2  26.0  72.0  42.0
3  72.0   NaN  85.0
4  95.0  24.0  48.0
5  39.0  78.0   NaN
6  30.0  11.0  80.0
7  55.0  71.0   8.0
8  91.0  29.0  96.0
9   NaN   NaN   NaN

In [129]:
df.notnull()# isnull()函数用于判断数据是否为缺失值(NaN)，返回一个布尔型的DataFrame或Series对象，缺失值为True，非缺失值为False。

       A      B      C
0   True   True   True
1   True   True   True
2   True   True   True
3   True  False   True
4   True   True   True
5   True   True  False
6   True   True   True
7   True   True   True
8   True   True   True
9  False  False  False

In [130]:
df.notnull().any(axis=1)# all()函数用于检查DataFrame或Series中是否所有值都为True。如果所有值都为True，返回True；否则返回False。默认情况下，all()函数沿着列方向（axis=0）进行操作，即检查每一列是否所有值都为True。如果希望沿着行方向（axis=1）进行操作，可以通过设置参数axis=1来实现。

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9    False
dtype: bool

In [128]:
df.loc[df.notnull().any(axis=1)]# df.notnull().all(axis=1)返回一个布尔型的Series对象，表示每一行是否所有值都为非缺失值。然后使用布尔索引df.loc[...]选择出所有值都为非缺失值的行。

      A     B     C
0  81.0  71.0  79.0
1  94.0  85.0  52.0
2  26.0  72.0  42.0
3  72.0   NaN  85.0
4  95.0  24.0  48.0
5  39.0  78.0   NaN
6  30.0  11.0  80.0
7  55.0  71.0   8.0
8  91.0  29.0  96.0

In [131]:
# 过滤掉A列中包含缺失值的行
df['A']

0    81.0
1    94.0
2    26.0
3    72.0
4    95.0
5    39.0
6    30.0
7    55.0
8    91.0
9     NaN
Name: A, dtype: float64

In [132]:
df['A'].notnull()# notnull()函数用于判断数据是否为非缺失值，返回一个布尔型的Series对象，非缺失值为True，缺失值为False。

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9    False
Name: A, dtype: bool

In [133]:
df.loc[df['A'].notnull()]

      A     B     C
0  81.0  71.0  79.0
1  94.0  85.0  52.0
2  26.0  72.0  42.0
3  72.0   NaN  85.0
4  95.0  24.0  48.0
5  39.0  78.0   NaN
6  30.0  11.0  80.0
7  55.0  71.0   8.0
8  91.0  29.0  96.0

- df.dropna()函数：删除所有包含缺失值的行，返回一个新的DataFrame对象。

In [134]:
df

      A     B     C
0  81.0  71.0  79.0
1  94.0  85.0  52.0
2  26.0  72.0  42.0
3  72.0   NaN  85.0
4  95.0  24.0  48.0
5  39.0  78.0   NaN
6  30.0  11.0  80.0
7  55.0  71.0   8.0
8  91.0  29.0  96.0
9   NaN   NaN   NaN

In [135]:
df.dropna()# dropna()函数用于删除所有包含缺失值的行，返回一个新的DataFrame对象。

      A     B     C
0  81.0  71.0  79.0
1  94.0  85.0  52.0
2  26.0  72.0  42.0
4  95.0  24.0  48.0
6  30.0  11.0  80.0
7  55.0  71.0   8.0
8  91.0  29.0  96.0

In [136]:
df.dropna(how='all')# dropna()函数用于删除所有包含缺失值的行，返回一个新的DataFrame对象。how='all'表示只删除所有值都为缺失值的行。

      A     B     C
0  81.0  71.0  79.0
1  94.0  85.0  52.0
2  26.0  72.0  42.0
3  72.0   NaN  85.0
4  95.0  24.0  48.0
5  39.0  78.0   NaN
6  30.0  11.0  80.0
7  55.0  71.0   8.0
8  91.0  29.0  96.0

In [ ]:
df.dropna(how='any', subset=['A', 'B'])# dropna()函数用于删除所有包含缺失值的行，返回一个新的DataFrame对象。how='any'表示只要有一个值为缺失值就删除该行。subset=['A', 'B']表示只考虑'A'和'B'列。

      A     B     C
0  81.0  71.0  79.0
1  94.0  85.0  52.0
2  26.0  72.0  42.0
4  95.0  24.0  48.0
5  39.0  78.0   NaN
6  30.0  11.0  80.0
7  55.0  71.0   8.0
8  91.0  29.0  96.0

## 异常值处理

### 异常值分析

#### 异常值是指在数据集中明显偏离其他观测值的数值。异常值可能是由于数据录入错误、测量误差或真实的极端情况引起的。在数据分析中，异常值可能会对统计分析和模型训练产生不利影响，因此需要进行处理。

- 使用describe()函数查看每一列的统计信息，包括均值、标准差、最小值、最大值等，可以帮助我们识别异常值。

### 异常值的认定

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns