# 1 美国各州人口密度分析

In [1]:
import numpy as np
import pandas as pd

## 1.1 首先导入文件，并查看数据样本

In [2]:
state_abbrevs = pd.read_csv('data/state-abbrevs.csv')
state_abbrevs.head()

        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [3]:
state_areas = pd.read_csv('data/state-areas.csv')
state_areas.head()

        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

In [4]:
state_population = pd.read_csv('data/state-population.csv')
state_population.head()

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [5]:
display(state_abbrevs.head(),state_areas.head(),state_population.head())

        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

## 1.2 合并state_abbrevs和state_populations数据集，分别根据abbreviation和state/region列进行合并，得到一个新的数据集state_info

In [6]:
state_info = pd.merge(left = state_population, right = state_abbrevs, how = 'outer', left_on = 'state/region', right_on = 'abbreviation')

In [7]:
state_info

     state/region     ages  year  population    state abbreviation
0              AK    total  1990    553290.0   Alaska           AK
1              AK  under18  1990    177502.0   Alaska           AK
2              AK    total  1992    588736.0   Alaska           AK
3              AK  under18  1991    182180.0   Alaska           AK
4              AK  under18  1992    184878.0   Alaska           AK
...           ...      ...   ...         ...      ...          ...
2539           WY  under18  1993    137458.0  Wyoming           WY
2540           WY    total  1991    459260.0  Wyoming           WY
2541           WY  under18  1991    136720.0  Wyoming           WY
2542           WY  under18  1990    136078.0  Wyoming           WY
2543           WY    total  1990    453690.0  Wyoming           WY

[2544 rows x 6 columns]

## 1.3 查看存在缺失数据的列

In [8]:
state_abbrevs.loc[:, 'abbreviation'].unique() # 查看state_abbrevs数据集中的abbreviation列中有哪些唯一值

<StringArray>
['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID',
 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM',
 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'PA',
 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY']
Length: 51, dtype: str

In [9]:
state_population.loc[:, 'state/region'].unique() # 查看state_population数据集中的state/region列中有哪些唯一值

<StringArray>
[ 'AL',  'AK',  'AZ',  'AR',  'CA',  'CO',  'CT',  'DE',  'DC',  'FL',  'GA',
  'HI',  'ID',  'IL',  'IN',  'IA',  'KS',  'KY',  'LA',  'ME',  'MD',  'MA',
  'MI',  'MN',  'MS',  'MO',  'MT',  'NE',  'NV',  'NH',  'NJ',  'NM',  'NY',
  'NC',  'ND',  'OH',  'OK',  'OR',  'PA',  'RI',  'SC',  'SD',  'TN',  'TX',
  'UT',  'VT',  'VA',  'WA',  'WV',  'WI',  'WY',  'PR', 'USA']
Length: 53, dtype: str

In [10]:
# PR 和 USA在state_population数据集中的state/region列中，但不在state_abbrevs数据集中的abbreviation列中
set(state_population.loc[:, 'state/region']) - set(state_abbrevs.loc[:, 'abbreviation']) # 查看state_population数据集中的state/region列中有哪些唯一值不在state_abbrevs数据集中的abbreviation列中

{'PR', 'USA'}

In [11]:
state_info.loc[:, 'state/region'].unique() # 查看state_info数据集中的state/region列中有哪些唯一值

<StringArray>
[ 'AK',  'AL',  'AR',  'AZ',  'CA',  'CO',  'CT',  'DC',  'DE',  'FL',  'GA',
  'HI',  'IA',  'ID',  'IL',  'IN',  'KS',  'KY',  'LA',  'MA',  'MD',  'ME',
  'MI',  'MN',  'MO',  'MS',  'MT',  'NC',  'ND',  'NE',  'NH',  'NJ',  'NM',
  'NV',  'NY',  'OH',  'OK',  'OR',  'PA',  'PR',  'RI',  'SC',  'SD',  'TN',
  'TX', 'USA',  'UT',  'VA',  'VT',  'WA',  'WI',  'WV',  'WY']
Length: 53, dtype: str

In [12]:
state_info.isnull().any() # 查看state_info数据集是否有缺失值

state/region    False
ages            False
year            False
population       True
state            True
abbreviation     True
dtype: bool

## 1.4 根据数据是否缺失情况显示数据，如果缺失为True，则显示

In [13]:
state_info.isnull().any(axis=1) # 查看state_info数据集是否有缺失值

0       False
1       False
2       False
3       False
4       False
        ...
2539    False
2540    False
2541    False
2542    False
2543    False
Length: 2544, dtype: bool

In [14]:
state_info.loc[state_info.isnull().any(axis=1)] # 根据数据是否缺失情况显示数据，如果缺失为True，则显示

     state/region     ages  year   population state abbreviation
1872           PR  under18  1990          NaN   NaN          NaN
1873           PR    total  1990          NaN   NaN          NaN
1874           PR    total  1991          NaN   NaN          NaN
1875           PR  under18  1991          NaN   NaN          NaN
1876           PR    total  1993          NaN   NaN          NaN
...           ...      ...   ...          ...   ...          ...
2203          USA    total  2010  309326295.0   NaN          NaN
2204          USA  under18  2011   73902222.0   NaN          NaN
2205          USA    total  2011  311582564.0   NaN          NaN
2206          USA  under18  2012   73708179.0   NaN          NaN
2207          USA    total  2012  313873685.0   NaN          NaN

[96 rows x 6 columns]

## 1.5 找到有哪些state/region使得state的值为Nan，使用unique()方法查看非重复值

In [15]:
state_info.loc[state_info.isnull().any(axis=1)].loc[:, 'state/region'].unique() # 找到有哪些state/region使得state的值为Nan，使用unique()方法查看非重复值

<StringArray>
['PR', 'USA']
Length: 2, dtype: str

## 1.6 为找到的这些state/region的state项补上正确的值，从而去掉state这一列的所有Nan

In [16]:
# 经过分析，只有PR和USA这两个state/region的state值为Nan，因此我们需要为这两个state/region的state项补上正确的值，从而去掉state这一列的所有Nan
# USA -> USA
# PR -> Puerto Rico

In [17]:
# 面积表中存在PR对应的州名为Puerto Rico
set(state_areas.loc[:, 'state'])-set(state_abbrevs.loc[:, 'state']) # 查看state_areas数据集中的state列中有哪些唯一值不在state_abbrevs数据集中的state列中

{'Puerto Rico'}

In [18]:
# 将state_info数据集中的PR对应的state项补上Puerto Rico
state_info.loc[state_info['state/region'] == 'PR', 'state'] = 'Puerto Rico'

In [19]:
state_info.loc[state_info.isnull().any(axis=1)] # 根据数据是否缺失情况显示数据，如果缺失为True，则显示

     state/region     ages  year   population        state abbreviation
1872           PR  under18  1990          NaN  Puerto Rico          NaN
1873           PR    total  1990          NaN  Puerto Rico          NaN
1874           PR    total  1991          NaN  Puerto Rico          NaN
1875           PR  under18  1991          NaN  Puerto Rico          NaN
1876           PR    total  1993          NaN  Puerto Rico          NaN
...           ...      ...   ...          ...          ...          ...
2203          USA    total  2010  309326295.0          NaN          NaN
2204          USA  under18  2011   73902222.0          NaN          NaN
2205          USA    total  2011  311582564.0          NaN          NaN
2206          USA  under18  2012   73708179.0          NaN          NaN
2207          USA    total  2012  313873685.0          NaN          NaN

[96 rows x 6 columns]

In [20]:
# 由于USA是全美国的数据，直接删掉
state_info.drop(state_info[state_info['state/region'] == 'USA'].index, inplace=True)

In [21]:
state_info.loc[:, 'state/region'].unique() # 查看state_info数据集中的state/region列中有哪些唯一值

<StringArray>
['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IA',
 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS',
 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA',
 'PR', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY']
Length: 52, dtype: str

In [22]:
state_info.isnull().any() # 查看state_info数据集是否有缺失值

state/region    False
ages            False
year            False
population       True
state           False
abbreviation     True
dtype: bool

In [23]:
state_info

     state/region     ages  year  population    state abbreviation
0              AK    total  1990    553290.0   Alaska           AK
1              AK  under18  1990    177502.0   Alaska           AK
2              AK    total  1992    588736.0   Alaska           AK
3              AK  under18  1991    182180.0   Alaska           AK
4              AK  under18  1992    184878.0   Alaska           AK
...           ...      ...   ...         ...      ...          ...
2539           WY  under18  1993    137458.0  Wyoming           WY
2540           WY    total  1991    459260.0  Wyoming           WY
2541           WY  under18  1991    136720.0  Wyoming           WY
2542           WY  under18  1990    136078.0  Wyoming           WY
2543           WY    total  1990    453690.0  Wyoming           WY

[2496 rows x 6 columns]

In [25]:
# 由于abbreviation列有空值，将这一列删除
state_info.drop('abbreviation', axis=1, inplace=True)

In [26]:
state_info

     state/region     ages  year  population    state
0              AK    total  1990    553290.0   Alaska
1              AK  under18  1990    177502.0   Alaska
2              AK    total  1992    588736.0   Alaska
3              AK  under18  1991    182180.0   Alaska
4              AK  under18  1992    184878.0   Alaska
...           ...      ...   ...         ...      ...
2539           WY  under18  1993    137458.0  Wyoming
2540           WY    total  1991    459260.0  Wyoming
2541           WY  under18  1991    136720.0  Wyoming
2542           WY  under18  1990    136078.0  Wyoming
2543           WY    total  1990    453690.0  Wyoming

[2496 rows x 5 columns]

## 1.7继续寻找存在缺失数据的列

In [29]:
# 找到population列中存在缺失值的行
state_info.loc[state_info.population.isnull()]

     state/region     ages  year  population        state
1872           PR  under18  1990         NaN  Puerto Rico
1873           PR    total  1990         NaN  Puerto Rico
1874           PR    total  1991         NaN  Puerto Rico
1875           PR  under18  1991         NaN  Puerto Rico
1876           PR    total  1993         NaN  Puerto Rico
1877           PR  under18  1993         NaN  Puerto Rico
1878           PR  under18  1992         NaN  Puerto Rico
1879           PR    total  1992         NaN  Puerto Rico
1880           PR  under18  1994         NaN  Puerto Rico
1881           PR    total  1994         NaN  Puerto Rico
1882           PR    total  1995         NaN  Puerto Rico
1883           PR  under18  1995         NaN  Puerto Rico
1884           PR  under18  1996         NaN  Puerto Rico
1885           PR    total  1996         NaN  Puerto Rico
1886           PR  under18  1998         NaN  Puerto Rico
1887           PR    total  1998         NaN  Puerto Rico
1888           PR    total  1997         NaN  Puerto Rico
1889           PR  under18  1997         NaN  Puerto Rico
1890           PR    total  1999         NaN  Puerto Rico
1891           PR  under18  1999         NaN  Puerto Rico

In [38]:
# 由于PR部分年份没有数据，将这部分删掉
state_info['population'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
2539    False
2540    False
2541    False
2542    False
2543    False
Name: population, Length: 2496, dtype: bool

In [45]:
pop_index = state_info.loc[state_info['population'].isnull()].index
pop_index

Index([1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883,
       1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891],
      dtype='int64')

In [46]:
state_info.drop(pop_index, axis=0, inplace=True)

In [49]:
state_info['population'].isnull().any() # 查看population列中是否还有缺失值

np.False_

In [51]:
# 法二
state_info = state_info.dropna()

## 1.8 合并各州面积数据

In [53]:
total = pd.merge(left = state_info, right = state_areas, how = 'outer', left_on = 'state', right_on = 'state')

In [54]:
total

     state/region     ages  year  population    state  area (sq. mi)
0              AL  under18  2012   1117489.0  Alabama          52423
1              AL    total  2012   4817528.0  Alabama          52423
2              AL  under18  2010   1130966.0  Alabama          52423
3              AL    total  2010   4785570.0  Alabama          52423
4              AL  under18  2011   1125763.0  Alabama          52423
...           ...      ...   ...         ...      ...            ...
2471           WY  under18  1993    137458.0  Wyoming          97818
2472           WY    total  1991    459260.0  Wyoming          97818
2473           WY  under18  1991    136720.0  Wyoming          97818
2474           WY  under18  1990    136078.0  Wyoming          97818
2475           WY    total  1990    453690.0  Wyoming          97818

[2476 rows x 6 columns]

## 1.9 找出2010年的全年总人口数据，df.query（查询语句）

In [76]:
pop_2010 = total.query('year == 2010 & ages == "total"') # 找出2010年的全年人口数据
pop_2010

,state/region,ages,year,population,state,area (sq. mi)
3,AL,total,2010,4785570.0,Alabama,52423
91,AK,total,2010,713868.0,Alaska,656425
101,AZ,total,2010,6408790.0,Arizona,114006
189,AR,total,2010,2922280.0,Arkansas,53182
197,CA,total,2010,37333601.0,California,163707
283,CO,total,2010,5048196.0,Colorado,104100
293,CT,total,2010,3579210.0,Connecticut,5544
379,DE,total,2010,899711.0,Delaware,1954
389,DC,total,2010,605125.0,District of Columbia,68
475,FL,total,2010,18846054.0,Florida,65758
485,GA,total,2010,9713248.0,Georgia,59441
570,HI,total,2010,1363731.0,Hawaii,10932
581,ID,total,2010,1570718.0,Idaho,83574
666,IL,total,2010,12839695.0,Illinois,57918
677,IN,total,2010,6489965.0,Indiana,36420
762,IA,total,2010,3050314.0,Iowa,56276
773,KS,total,2010,2858910.0,Kansas,82282
858,KY,total,2010,4347698.0,Kentucky,40411
869,LA,total,2010,4545392.0,Louisiana,51843
954,ME,total,2010,1327366.0,Maine,35387
965,MD,total,2010,5787193.0,Maryland,12407
1050,MA,total,2010,6563263.0,Massachusetts,10555
1061,MI,total,2010,9876149.0,Michigan,96810
1146,MN,total,2010,5310337.0,Minnesota,86943
1157,MS,total,2010,2970047.0,Mississippi,48434
1242,MO,total,2010,5996063.0,Missouri,69709
1253,MT,total,2010,990527.0,Montana,147046
1338,NE,total,2010,1829838.0,Nebraska,77358
1349,NV,total,2010,2703230.0,Nevada,110567
1434,NH,total,2010,1316614.0,New Hampshire,9351
1445,NJ,total,2010,8802707.0,New Jersey,8722
1530,NM,total,2010,2064982.0,New Mexico,121593
1541,NY,total,2010,19398228.0,New York,54475
1626,NC,total,2010,9559533.0,North Carolina,53821
1637,ND,total,2010,674344.0,North Dakota,70704
1722,OH,total,2010,11545435.0,Ohio,44828
1733,OK,total,2010,3759263.0,Oklahoma,69903
1818,OR,total,2010,3837208.0,Oregon,98386
1829,PA,total,2010,12710472.0,Pennsylvania,46058
1894,PR,total,2010,3721208.0,Puerto Rico,3515
1942,RI,total,2010,1052669.0,Rhode Island,1545
1953,SC,total,2010,4636361.0,South Carolina,32007
2038,SD,total,2010,816211.0,South Dakota,77121
2049,TN,total,2010,6356683.0,Tennessee,42146
2134,TX,total,2010,25245178.0,Texas,268601
2145,UT,total,2010,2774424.0,Utah,84904
2230,VT,total,2010,625793.0,Vermont,9615
2241,VA,total,2010,8024417.0,Virginia,42769
2326,WA,total,2010,6742256.0,Washington,71303
2337,WV,total,2010,1854146.0,West Virginia,24231
2422,WI,total,2010,5689060.0,Wisconsin,65503
2433,WY,total,2010,564222.0,Wyoming,97818

In [69]:
total['year'] == 2010

0       False
1       False
2        True
3        True
4       False
        ...
2471    False
2472    False
2473    False
2474    False
2475    False
Name: year, Length: 2476, dtype: bool

In [70]:
total['ages'] == 'total'

0       False
1        True
2       False
3        True
4       False
        ...
2471    False
2472     True
2473    False
2474    False
2475     True
Name: ages, Length: 2476, dtype: bool

In [73]:
con = (total['year'] == 2010) & (total['ages'] == 'total') # 找出2010年的全年人口数据

In [77]:
total.loc[con] # 根据条件con显示数据

,state/region,ages,year,population,state,area (sq. mi)
3,AL,total,2010,4785570.0,Alabama,52423
91,AK,total,2010,713868.0,Alaska,656425
101,AZ,total,2010,6408790.0,Arizona,114006
189,AR,total,2010,2922280.0,Arkansas,53182
197,CA,total,2010,37333601.0,California,163707
283,CO,total,2010,5048196.0,Colorado,104100
293,CT,total,2010,3579210.0,Connecticut,5544
379,DE,total,2010,899711.0,Delaware,1954
389,DC,total,2010,605125.0,District of Columbia,68
475,FL,total,2010,18846054.0,Florida,65758
485,GA,total,2010,9713248.0,Georgia,59441
570,HI,total,2010,1363731.0,Hawaii,10932
581,ID,total,2010,1570718.0,Idaho,83574
666,IL,total,2010,12839695.0,Illinois,57918
677,IN,total,2010,6489965.0,Indiana,36420
762,IA,total,2010,3050314.0,Iowa,56276
773,KS,total,2010,2858910.0,Kansas,82282
858,KY,total,2010,4347698.0,Kentucky,40411
869,LA,total,2010,4545392.0,Louisiana,51843
954,ME,total,2010,1327366.0,Maine,35387
965,MD,total,2010,5787193.0,Maryland,12407
1050,MA,total,2010,6563263.0,Massachusetts,10555
1061,MI,total,2010,9876149.0,Michigan,96810
1146,MN,total,2010,5310337.0,Minnesota,86943
1157,MS,total,2010,2970047.0,Mississippi,48434
1242,MO,total,2010,5996063.0,Missouri,69709
1253,MT,total,2010,990527.0,Montana,147046
1338,NE,total,2010,1829838.0,Nebraska,77358
1349,NV,total,2010,2703230.0,Nevada,110567
1434,NH,total,2010,1316614.0,New Hampshire,9351
1445,NJ,total,2010,8802707.0,New Jersey,8722
1530,NM,total,2010,2064982.0,New Mexico,121593
1541,NY,total,2010,19398228.0,New York,54475
1626,NC,total,2010,9559533.0,North Carolina,53821
1637,ND,total,2010,674344.0,North Dakota,70704
1722,OH,total,2010,11545435.0,Ohio,44828
1733,OK,total,2010,3759263.0,Oklahoma,69903
1818,OR,total,2010,3837208.0,Oregon,98386
1829,PA,total,2010,12710472.0,Pennsylvania,46058
1894,PR,total,2010,3721208.0,Puerto Rico,3515
1942,RI,total,2010,1052669.0,Rhode Island,1545
1953,SC,total,2010,4636361.0,South Carolina,32007
2038,SD,total,2010,816211.0,South Dakota,77121
2049,TN,total,2010,6356683.0,Tennessee,42146
2134,TX,total,2010,25245178.0,Texas,268601
2145,UT,total,2010,2774424.0,Utah,84904
2230,VT,total,2010,625793.0,Vermont,9615
2241,VA,total,2010,8024417.0,Virginia,42769
2326,WA,total,2010,6742256.0,Washington,71303
2337,WV,total,2010,1854146.0,West Virginia,24231
2422,WI,total,2010,5689060.0,Wisconsin,65503
2433,WY,total,2010,564222.0,Wyoming,97818

## 1.10 对查询结果进行处理，以state列作为新的行索引：set_index()方法

In [78]:
total.set_index('state', inplace=True)

In [79]:
total

        state/region     ages  year  population  area (sq. mi)
state
Alabama           AL  under18  2012   1117489.0          52423
Alabama           AL    total  2012   4817528.0          52423
Alabama           AL  under18  2010   1130966.0          52423
Alabama           AL    total  2010   4785570.0          52423
Alabama           AL  under18  2011   1125763.0          52423
...              ...      ...   ...         ...            ...
Wyoming           WY  under18  1993    137458.0          97818
Wyoming           WY    total  1991    459260.0          97818
Wyoming           WY  under18  1991    136720.0          97818
Wyoming           WY  under18  1990    136078.0          97818
Wyoming           WY    total  1990    453690.0          97818

[2476 rows x 5 columns]

## 1.11 计算各州人口密度，使用人口总数除以面积，得到一个新的列density

In [82]:
total['density'] = total['population'] / total['area (sq. mi)'] # 计算各州人口密度，使用人口总数除以面积，得到一个新的列density

In [83]:
total

        state/region     ages  year  population  area (sq. mi)    density
state
Alabama           AL  under18  2012   1117489.0          52423  21.316769
Alabama           AL    total  2012   4817528.0          52423  91.897221
Alabama           AL  under18  2010   1130966.0          52423  21.573851
Alabama           AL    total  2010   4785570.0          52423  91.287603
Alabama           AL  under18  2011   1125763.0          52423  21.474601
...              ...      ...   ...         ...            ...        ...
Wyoming           WY  under18  1993    137458.0          97818   1.405242
Wyoming           WY    total  1991    459260.0          97818   4.695046
Wyoming           WY  under18  1991    136720.0          97818   1.397698
Wyoming           WY  under18  1990    136078.0          97818   1.391135
Wyoming           WY    total  1990    453690.0          97818   4.638103

[2476 rows x 6 columns]

## 1.12 对查询结果进行排序

In [86]:
total.sort_values(by='density', ascending=True, inplace=True)

In [87]:
total

,state/region,ages,year,population,area (sq. mi),density
state,,,,,,
Alaska,AK,under18,1990,177502.0,656425,0.270407
Alaska,AK,under18,1991,182180.0,656425,0.277534
Alaska,AK,under18,2008,183124.0,656425,0.278972
Alaska,AK,under18,2007,184344.0,656425,0.280830
Alaska,AK,under18,1992,184878.0,656425,0.281644
...,...,...,...,...,...,...
District of Columbia,DC,total,2010,605125.0,68,8898.897059
District of Columbia,DC,total,1990,605321.0,68,8901.779412
District of Columbia,DC,total,2011,619624.0,68,9112.117647
District of Columbia,DC,total,2012,633427.0,68,9315.102941
District of Columbia,DC,total,2013,646449.0,68,9506.602941