# Pandas时间序列与日期

## 1.1 时间构造函数

### 1.1 pandas构造时间的函数

In [219]:
import numpy as np
import pandas as pd
import datetime

In [220]:
# python自带度datetime模块
now = datetime.datetime.now()  # 获取当前时间
type(now)

datetime.datetime

In [221]:
# panda
now1 = pd.Timestamp.now()  # 获取当前时间

In [222]:
now1

Timestamp('2026-07-16 15:01:44.863210')

In [223]:
type(now1)

pandas.Timestamp

In [224]:
now.date()# 获取日期

datetime.date(2026, 7, 16)

In [225]:
now.time()# 获取时间

datetime.time(15, 1, 44, 857479)

In [226]:
now.year, now.month, now.day, now.hour, now.minute, now.second

(2026, 7, 16, 15, 1, 44)

In [227]:
now.strftime('%Y-%m-%d %H:%M:%S')  # 格式化时间

'2026-07-16 15:01:44'

### 1.1.2 时间戳pd.Timestamp和时间段pd.Period

pandas.Timestamp() 用于表示一个具体的日期和时间，可以理解为 pandas 版本的 Python datetime.datetime。它主要处理单个时间点

In [228]:
pd.Timestamp('2023-01-01')  # 时间戳

Timestamp('2023-01-01 00:00:00')

| `freq` | 含义 |<br>
| `"s"` | 每秒 |<br>
| `"min"` | 每分钟 |<br>   
| `"h"` | 每小时 |<br>
| `"D"` | 每天 |<br>
| `"W"` | 每周，默认周日结束 |<br>
| `"W-MON"` | 每周一 |<br>
| `"MS"` | 每月月初 |<br>
| `"ME"` | 每月月末 |<br>
| `"QS"` | 每季度初 |<br>
| `"QE"` | 每季度末 |<br>
| `"YS"` | 每年年初 |<br>
| `"YE"` | 每年年末 |<br>
| `"B"` | 每个工作日，跳过周六、周日 |<br>

In [229]:
# period表示单个时间段，freq表示时间段的频率，M表示月，D表示日，H表示小时，S表示秒,对 Period 来说，freq 决定这个对象代表多长的时间
ts = pd.Period('2023-01-02',freq='M')  
display(ts,type(ts))

Period('2023-01', 'M')

pandas.Period

In [230]:
ts + 1 # 添加1月

Period('2023-02', 'M')

In [231]:
pd.Period('2023-01-02',freq='D')

Period('2023-01-02', 'D')

timestamp与period可以作为索引使用，作为索引时，timestamp表示一个时间点，period表示一个时间段。<br>
作为索引的timestamp和period列表则被强制转换为对应的DatetimeIndex和PeriodIndex。<br>

In [232]:
date = [pd.Timestamp('2023-01-01'), pd.Timestamp('2023-01-02'), pd.Timestamp('2023-01-03')]
date

[Timestamp('2023-01-01 00:00:00'),
 Timestamp('2023-01-02 00:00:00'),
 Timestamp('2023-01-03 00:00:00')]

In [233]:
ts = pd.Series(data = np.random.randint(1,10,3), index = date)

In [234]:
ts

2023-01-01    5
2023-01-02    6
2023-01-03    6
dtype: int64

In [235]:
ts.index

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03'], dtype='datetime64[us]', freq=None)

In [236]:
date = [pd.Period('2023-01-01', freq='D'), pd.Period('2023-01-02', freq='D'), pd.Period('2023-01-03', freq='D')]

In [237]:
date

[Period('2023-01-01', 'D'),
 Period('2023-01-02', 'D'),
 Period('2023-01-03', 'D')]

In [238]:
ts = pd.Series(data = np.random.randint(1,10,3), index = date)

In [239]:
ts

2023-01-01    3
2023-01-02    1
2023-01-03    8
Freq: D, dtype: int64

In [240]:
ts.index

PeriodIndex(['2023-01-01', '2023-01-02', '2023-01-03'], dtype='period[D]')

### 1.1.3 构造时间序列date_range\bdate_range()

- 实际工作中，经常要生成含大量时间戳的超长索引，一个个输入时间戳显然不现实
- 如果时间戳是定频的，用`pd.date_range()`或`pd.bdate_range()`可以快速生成时间戳序列
- dange_range()默认生成的是日历日的时间戳序列，bdate_range()默认生成的是工作日的时间戳序列

In [241]:
pd.date_range(start='2023-01-01', end='2023-01-10', freq='2D')  # 生成时间戳序列

DatetimeIndex(['2023-01-01', '2023-01-03', '2023-01-05', '2023-01-07',
               '2023-01-09'],
              dtype='datetime64[us]', freq='2D')

In [242]:
pd.bdate_range(start='2022-02-01', end='2022-02-16', freq='B')  # 生成工作日时间戳序列

DatetimeIndex(['2022-02-01', '2022-02-02', '2022-02-03', '2022-02-04',
               '2022-02-07', '2022-02-08', '2022-02-09', '2022-02-10',
               '2022-02-11', '2022-02-14', '2022-02-15', '2022-02-16'],
              dtype='datetime64[us]', freq='B')

In [243]:
pd.date_range(start='2023-01-01', periods=10, freq='2D')  # 指定开始时间和时间段数，生成时间戳序列

DatetimeIndex(['2023-01-01', '2023-01-03', '2023-01-05', '2023-01-07',
               '2023-01-09', '2023-01-11', '2023-01-13', '2023-01-15',
               '2023-01-17', '2023-01-19'],
              dtype='datetime64[us]', freq='2D')

In [244]:
pd.date_range(start='2023-01-01', end='2023-01-9',periods=3)  # 指定开始时间和结束时间和时间段数，生成时间戳序列

DatetimeIndex(['2023-01-01', '2023-01-05', '2023-01-09'], dtype='datetime64[us]', freq=None)

## 1.2 转换时间戳

### 1.2.1 to_datetime()实现批量日期转换

to_datetime()函数可以将字符串、纪元式及混合的日期Series或者日期列表转换为pandas的时间戳类型，返回一个DatetimeIndex对象。<br>
转换的是Series时，返回的是一个Series对象，索引不变，值为时间戳类型。<br>
转换的是列表时，返回的是一个DatetimeIndex对象。<br>

pandas可以识别的日期格式有：
- '%Y-%m-%d' (例如: 2023-01-01)
- '%Y/%m/%d' (例如: 2023/01/01)
- '%Y.%m.%d' (例如: 2023.01.01)

In [245]:
s = pd.Series([
    '2005/11/23',
    '2010.06.24',
    'Jul,31, 2009',
    '2012-09-08',
    'Aug-09-2011',
    'Feb 1 2010',
    '01-14-2012',
    None],name='date')

In [246]:
s

0      2005/11/23
1      2010.06.24
2    Jul,31, 2009
3      2012-09-08
4     Aug-09-2011
5      Feb 1 2010
6      01-14-2012
7             NaN
Name: date, dtype: str

In [247]:
df = pd.DataFrame(data = s)
df

           date
0    2005/11/23
1    2010.06.24
2  Jul,31, 2009
3    2012-09-08
4   Aug-09-2011
5    Feb 1 2010
6    01-14-2012
7           NaN

In [248]:
df['value'] = np.random.randint(1,10,8)
df

           date  value
0    2005/11/23      4
1    2010.06.24      8
2  Jul,31, 2009      4
3    2012-09-08      2
4   Aug-09-2011      3
5    Feb 1 2010      9
6    01-14-2012      3
7           NaN      2

In [249]:
df.sort_values(by = 'date') # 不是按照时间戳排序，而是按照字符串排序

           date  value
6    01-14-2012      3
0    2005/11/23      4
1    2010.06.24      8
3    2012-09-08      2
4   Aug-09-2011      3
5    Feb 1 2010      9
2  Jul,31, 2009      4
7           NaN      2

In [250]:
pd.to_datetime(df['date'], format='mixed', errors='coerce')  # 将字符串转换为时间戳

0   2005-11-23
1   2010-06-24
2   2009-07-31
3   2012-09-08
4   2011-08-09
5   2010-02-01
6   2012-01-14
7          NaT
Name: date, dtype: datetime64[us]

#### 时间类型的字符串，可以直接使用to_datetime()函数转换为Timestamp类型，转换后的时间戳可以直接进行时间运算。<br>
#### 并且空值会被自动转换为NaT类型，NaT是pandas中时间戳的空值类型。<br>

In [251]:
df['date'] = pd.to_datetime(df['date'], format='mixed', errors='coerce')  # 将字符串转换为时间戳类型

In [252]:
df

        date  value
0 2005-11-23      4
1 2010-06-24      8
2 2009-07-31      4
3 2012-09-08      2
4 2011-08-09      3
5 2010-02-01      9
6 2012-01-14      3
7        NaT      2

In [253]:
df.sort_values(by='date',ascending=True)

        date  value
0 2005-11-23      4
2 2009-07-31      4
5 2010-02-01      9
1 2010-06-24      8
4 2011-08-09      3
6 2012-01-14      3
3 2012-09-08      2
7        NaT      2

解析欧式日期（日-月-年），要用dayfirst=True参数，解析美式日期（月-日-年），要用dayfirst=False参数。<br>

In [254]:
pd.to_datetime('04-01-2023', dayfirst=True)  # 解析欧式日期（日-月-年）

Timestamp('2023-01-04 00:00:00')

In [255]:
pd.to_datetime('04-01-2023', dayfirst=False)  # 解析美式日期（月-日-年）

Timestamp('2023-04-01 00:00:00')

dayfirst并没有那么严苛，如果不能把第一个数字解释为日，则会尝试把第一个数字解释为月。<br>

In [256]:
pd.to_datetime(['2023-01-01', '02-14-2023'], dayfirst=True, format='mixed')  # 将字符串列表转换为时间戳类型

DatetimeIndex(['2023-01-01', '2023-02-14'], dtype='datetime64[us]', freq=None)

In [257]:
# to_datetime()转换单个字符串时，返回的是Timestamp类型，转换多个字符串时，返回的是DatetimeIndex类型。
pd.to_datetime('2023-01-01')  # 单个字符串

Timestamp('2023-01-01 00:00:00')

Timestamp函数仅支持单个字符串的转换，不支持dayfirst、format参数。如果要使用dayfirst、format参数，需要使用to_datetime()函数。<br>

In [258]:
 # 指定格式转换,format参数指定字符串的格式，%Y表示四位数的年份，%m表示两位数的月份，%d表示两位数的日期
pd.to_datetime('2023年01月01日', format='%Y年%m月%d日')

Timestamp('2023-01-01 00:00:00')

### 1.2.2 DatetimeIndex构造

#### Pandas还支持直接使用DatetimeIndex构造函数来构造DatetimeIndex对象，DatetimeIndex构造函数的参数与to_datetime()函数类似。

In [259]:
pd.DatetimeIndex(['2023-01-01', '2023-02-14'])  # 将字符串列表转换为DatetimeIndex类型

DatetimeIndex(['2023-01-01', '2023-02-14'], dtype='datetime64[us]', freq=None)

#### 创建DatetimeIndex时，freq=’infer‘可以让pandas自动推断时间戳的频率，freq参数可以指定时间戳的频率。

In [260]:
time_index = pd.DatetimeIndex(['2023-01-01', '2023-01-03', '2023-01-05'], freq='infer')  # 创建DatetimeIndex时，freq=’infer‘可以让pandas自动推断时间戳的频率，freq参数可以指定时间戳的频率。

In [261]:
time_index

DatetimeIndex(['2023-01-01', '2023-01-03', '2023-01-05'], dtype='datetime64[us]', freq='2D')

In [262]:
time_index[0]  # 获取第一个时间戳

Timestamp('2023-01-01 00:00:00')

### 1.2.3 提供格式参数format

要实现精确转换，除了传递datatime字符串，还可以通过format参数指定时间字符串的格式，format参数的值是一个格式化字符串，格式化字符串的含义与Python标准库中的datetime模块相同。

%Y: 四位数的年份表示（0000-9999）<br>
%m: 月份（01-12）<br>
%d: 月内中的一天（0-31）<br>
%H: 小时（24小时制）（00-23）<br>
%M: 分钟数（00=59）<br> 
%S: 秒（00-59）<br>

### 1.2.4 无效数据

不可解析时，默认值errors='raise'，会抛出异常。可以通过errors参数指定错误处理方式，errors参数的可选值有：
- 'raise'：抛出异常，默认值
- 'coerce'：将无法解析的值设置为NaT

In [263]:
index = pd.to_datetime(['2023-01-01', 'asdf'], errors='coerce')  # 将字符串列表转换为时间戳类型，无法解析的值会被设置为NaT

In [264]:
index[0],index[1]  # 获取第一个时间戳和第二个时间戳

(Timestamp('2023-01-01 00:00:00'), NaT)

In [265]:
data=pd.Series(data = ['2012-01-01','sade', '2013年01月01日',None],name='date')  # 创建一个包含无效数据的Series对象

In [266]:
data

0     2012-01-01
1           sade
2    2013年01月01日
3            NaN
Name: date, dtype: str

In [267]:
def transform_date(date_str):
    # 处理无效数据
    if pd.isna(date_str):#pd.isna可以判断是否为缺失值，缺失值包括None和NaN
        return pd.NaT
    # 处理中文日期格式
    if date_str.endswith('年') or date_str.endswith('月') or date_str.endswith('日'):
        return pd.to_datetime(date_str, format='%Y年%m月%d日', errors='coerce')  # 将字符串转换为时间戳类型，无法解析的值会被设置为NaT
    else:# 处理字符串
        obj = pd.to_datetime(date_str, format='mixed', errors='coerce')  # 将字符串转换为时间戳类型，无法解析的值会被设置为NaT
        return obj

In [268]:
data.map(transform_date)  # 使用map()方法将transform_date函数应用于Series对象的每个元素

0   2012-01-01
1          NaT
2   2013-01-01
3          NaT
Name: date, dtype: datetime64[us]

## 1.3 索引访问

### 1.3.1 常规索引访问

datetimeIndex对象和PeriodIndex对象都支持常规索引访问，支持整数索引、切片索引、布尔索引、花式索引等。

In [269]:
pd.date_range(start='2023-01-01', periods=20, freq='ME')  # 生成时间戳序列，freq='M'表示按月生成时间戳

DatetimeIndex(['2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-30', '2023-10-31', '2023-11-30', '2023-12-31',
               '2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31'],
              dtype='datetime64[us]', freq='ME')

In [270]:
ts = pd.Series(data = np.random.randint(1,10,20), index = pd.date_range(start='2023-01-01', periods=20, freq='ME'))  # 创建一个以时间戳为索引的Series对象

In [271]:
ts

2023-01-31    1
2023-02-28    5
2023-03-31    2
2023-04-30    1
2023-05-31    6
2023-06-30    6
2023-07-31    6
2023-08-31    9
2023-09-30    5
2023-10-31    6
2023-11-30    5
2023-12-31    2
2024-01-31    5
2024-02-29    6
2024-03-31    2
2024-04-30    3
2024-05-31    8
2024-06-30    4
2024-07-31    4
2024-08-31    9
Freq: ME, dtype: int64

In [272]:
ts.index

DatetimeIndex(['2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-30', '2023-10-31', '2023-11-30', '2023-12-31',
               '2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31'],
              dtype='datetime64[us]', freq='ME')

In [273]:
ts.index[0]  # 使用整数索引访问第一个元素

Timestamp('2023-01-31 00:00:00')

In [274]:
ts.index[-1]  # 使用整数索引访问最后一个元素

Timestamp('2024-08-31 00:00:00')

In [275]:
ts.index[0:5]  # 使用切片索引访问前五个元素

DatetimeIndex(['2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31'],
              dtype='datetime64[us]', freq='ME')

### 1.3.2 局部字符串索引

能解析为时间戳的日期与字符串可以作为索引的参数：

pandas为访问较长的时间序列提供了便捷方法，年、年月字符串可以作为索引参数，访问对应的时间戳数据。<br>
带DatetimeIndex的dataframe或series对象可以使用局部字符串索引访问数据，局部字符串时标签切片的一种形式，局部字符串索引的切片是闭区间，包含起始和结束时间。<br>

In [276]:
# 前提datatimeindex对象作为索引
ts['2023']

2023-01-31    1
2023-02-28    5
2023-03-31    2
2023-04-30    1
2023-05-31    6
2023-06-30    6
2023-07-31    6
2023-08-31    9
2023-09-30    5
2023-10-31    6
2023-11-30    5
2023-12-31    2
Freq: ME, dtype: int64

In [277]:
ts['2023-01']  # 使用局部字符串索引访问2023年1月的数据

2023-01-31    1
Freq: ME, dtype: int64

In [278]:
ts['2023-01':'2023-05']  # 使用局部字符串索引访问2023年1月的数据

2023-01-31    1
2023-02-28    5
2023-03-31    2
2023-04-30    1
2023-05-31    6
Freq: ME, dtype: int64

In [282]:
aapl = pd.read_csv('AAPL.csv')

In [283]:
aapl.info()

<class 'pandas.DataFrame'>
RangeIndex: 10665 entries, 0 to 10664
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       10665 non-null  str
 1   Open       10665 non-null  float64
 2   High       10665 non-null  float64
 3   Low        10665 non-null  float64
 4   Close      10665 non-null  float64
 5   Adj Close  10665 non-null  float64
 6   Volume     10665 non-null  int64
dtypes: float64(5), int64(1), str(1)
memory usage: 583.4 KB

In [284]:
aapl.head()  # 查看前五行数据

         Date      Open      High       Low     Close  Adj Close     Volume
0  1980-12-12  0.128348  0.128906  0.128348  0.128348   0.099722  469033600
1  1980-12-15  0.122210  0.122210  0.121652  0.121652   0.094519  175884800
2  1980-12-16  0.113281  0.113281  0.112723  0.112723   0.087582  105728000
3  1980-12-17  0.115513  0.116071  0.115513  0.115513   0.089749   86441600
4  1980-12-18  0.118862  0.119420  0.118862  0.118862   0.092351   73449600

In [285]:
aapl['Date'] = pd.to_datetime(aapl['Date'], format='mixed', errors='coerce')  # 将字符串转换为时间戳类型，无法解析的值会被设置为NaT

In [286]:
aapl.info()  # 查看数据类型和缺失值情况

<class 'pandas.DataFrame'>
RangeIndex: 10665 entries, 0 to 10664
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       10665 non-null  datetime64[us]
 1   Open       10665 non-null  float64
 2   High       10665 non-null  float64
 3   Low        10665 non-null  float64
 4   Close      10665 non-null  float64
 5   Adj Close  10665 non-null  float64
 6   Volume     10665 non-null  int64
dtypes: datetime64[us](1), float64(5), int64(1)
memory usage: 583.4 KB

In [287]:
aapl.set_index('Date', inplace=True)  # 将Date列设置为索引

In [288]:
aapl

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
1980-12-12,0.128348,0.128906,0.128348,0.128348,0.099722,469033600
1980-12-15,0.122210,0.122210,0.121652,0.121652,0.094519,175884800
1980-12-16,0.113281,0.113281,0.112723,0.112723,0.087582,105728000
1980-12-17,0.115513,0.116071,0.115513,0.115513,0.089749,86441600
1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092351,73449600
...,...,...,...,...,...,...
2023-03-27,159.940002,160.770004,157.869995,158.279999,158.279999,52390300
2023-03-28,157.970001,158.490005,155.979996,157.649994,157.649994,45992200
2023-03-29,159.369995,161.050003,159.350006,160.770004,160.770004,51305700
2023-03-30,161.529999,162.470001,161.270004,162.360001,162.360001,49501700
2023-03-31,162.440002,165.000000,161.910004,164.899994,164.899994,68694700

In [289]:
aapl.info()  # 查看数据类型和缺失值情况

<class 'pandas.DataFrame'>
DatetimeIndex: 10665 entries, 1980-12-12 to 2023-03-31
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Open       10665 non-null  float64
 1   High       10665 non-null  float64
 2   Low        10665 non-null  float64
 3   Close      10665 non-null  float64
 4   Adj Close  10665 non-null  float64
 5   Volume     10665 non-null  int64
dtypes: float64(5), int64(1)
memory usage: 583.2 KB

In [290]:
aapl.loc['2023-01']  # 使用局部字符串索引访问2023年1月的数据

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-01-03,130.279999,130.899994,124.169998,125.070000,124.879326,112117500
2023-01-04,126.889999,128.660004,125.080002,126.360001,126.167366,89113600
2023-01-05,127.129997,127.769997,124.760002,125.019997,124.829399,80962700
2023-01-06,126.010002,130.289993,124.889999,129.619995,129.422394,87754700
2023-01-09,130.470001,133.410004,129.889999,130.149994,129.951584,70790800
2023-01-10,130.259995,131.259995,128.119995,130.729996,130.530701,63896200
2023-01-11,131.250000,133.509995,130.460007,133.490005,133.286499,69458900
2023-01-12,133.880005,134.259995,131.440002,133.410004,133.206619,71379600
2023-01-13,132.029999,134.919998,131.660004,134.759995,134.554550,57809700
2023-01-17,134.830002,137.289993,134.130005,135.940002,135.732758,63646600
2023-01-18,136.820007,138.610001,135.029999,135.210007,135.003876,69672800
2023-01-19,134.080002,136.250000,133.770004,135.270004,135.063782,58280400
2023-01-20,135.279999,138.020004,134.220001,137.869995,137.659805,80223600
2023-01-23,138.119995,143.320007,137.899994,141.110001,140.894882,81760300
2023-01-24,140.309998,143.160004,140.300003,142.529999,142.312714,66435100
2023-01-25,140.889999,142.429993,138.809998,141.860001,141.643738,65799300
2023-01-26,143.169998,144.250000,141.899994,143.960007,143.740540,54105100
2023-01-27,143.160004,147.229996,143.080002,145.929993,145.707520,70555800
2023-01-30,144.960007,145.550003,142.850006,143.000000,142.781998,64015300
2023-01-31,142.699997,144.339996,142.279999,144.289993,144.070023,65874500

## 1.4 日期/时间属性

以下日期/时间属性可以直接访问Timestamp对象或DatetimeIndex对象。<br>
- year: 年份
- month: 月份
- day: 日
- hour: 小时
- minute: 分钟
- second: 秒
- microsecond: 微秒
- nanosecond: 纳秒
- date: 日期
- time: 时间
- tz: 时区
- dayofyear: 一年中的第几天
- dayofweek: 一周中的第几天，周一为0，周日为6
- week: 一年中的第几周
- dayofweek: 一周中的第几天，周一为0，周日为6
- weekday: 一周中的第几天，周一为0，周日为6
- weekday_name: 一周中的第几天的名称
- quarter: 季度
- days_in_month: 当月的天数
- is_month_start: 是否为月初
- is_month_end: 是否为月末
- is_quarter_start: 是否为季度初
- is_quarter_end: 是否为季度末
- is_year_start: 是否为年初
- is_year_end: 是否为年末
- is_leap_year: 是否为闰年

In [295]:
t = pd.Timestamp('2023-01-01 12:00:00')  # 时间戳
t

Timestamp('2023-01-01 12:00:00')

In [296]:
t.year

2023

In [297]:
t.quarter

1

In [298]:
t.is_year_end

False

In [299]:
ts = pd.DatetimeIndex(data= pd.date_range(start='2023-01-01', periods=10, freq='2D'))

In [300]:
ts

DatetimeIndex(['2023-01-01', '2023-01-03', '2023-01-05', '2023-01-07',
               '2023-01-09', '2023-01-11', '2023-01-13', '2023-01-15',
               '2023-01-17', '2023-01-19'],
              dtype='datetime64[us]', freq='2D')

In [301]:
ts.year

Index([2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023], dtype='int32')

In [302]:
ts.month

Index([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype='int32')

In [303]:
ts.is_month_start

array([ True, False, False, False, False, False, False, False, False,
       False])

## 1.5 pandas对象的dt属性

Series对象和DataFrame对象的列可以通过dt属性访问日期/时间属性。<br>
对应日期时间数据，通过这个接口可以快速实现特定的功能，非常快捷。<br>

In [320]:
aapl

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
1980-12-12,0.128348,0.128906,0.128348,0.128348,0.099722,469033600
1980-12-15,0.122210,0.122210,0.121652,0.121652,0.094519,175884800
1980-12-16,0.113281,0.113281,0.112723,0.112723,0.087582,105728000
1980-12-17,0.115513,0.116071,0.115513,0.115513,0.089749,86441600
1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092351,73449600
...,...,...,...,...,...,...
2023-03-27,159.940002,160.770004,157.869995,158.279999,158.279999,52390300
2023-03-28,157.970001,158.490005,155.979996,157.649994,157.649994,45992200
2023-03-29,159.369995,161.050003,159.350006,160.770004,160.770004,51305700
2023-03-30,161.529999,162.470001,161.270004,162.360001,162.360001,49501700
2023-03-31,162.440002,165.000000,161.910004,164.899994,164.899994,68694700

In [321]:
AAPL = pd.read_csv('AAPL.csv')

In [322]:
AAPL

,Date,Open,High,Low,Close,Adj Close,Volume
0,1980-12-12,0.128348,0.128906,0.128348,0.128348,0.099722,469033600
1,1980-12-15,0.122210,0.122210,0.121652,0.121652,0.094519,175884800
2,1980-12-16,0.113281,0.113281,0.112723,0.112723,0.087582,105728000
3,1980-12-17,0.115513,0.116071,0.115513,0.115513,0.089749,86441600
4,1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092351,73449600
...,...,...,...,...,...,...,...
10660,2023-03-27,159.940002,160.770004,157.869995,158.279999,158.279999,52390300
10661,2023-03-28,157.970001,158.490005,155.979996,157.649994,157.649994,45992200
10662,2023-03-29,159.369995,161.050003,159.350006,160.770004,160.770004,51305700
10663,2023-03-30,161.529999,162.470001,161.270004,162.360001,162.360001,49501700
10664,2023-03-31,162.440002,165.000000,161.910004,164.899994,164.899994,68694700

In [323]:
AAPL['Date'] = pd.to_datetime(AAPL['Date'], format='mixed', errors='coerce')  # 将字符串转换为时间戳类型，无法解析的值会被设置为NaT

In [324]:
AAPL.head()

        Date      Open      High       Low     Close  Adj Close     Volume
0 1980-12-12  0.128348  0.128906  0.128348  0.128348   0.099722  469033600
1 1980-12-15  0.122210  0.122210  0.121652  0.121652   0.094519  175884800
2 1980-12-16  0.113281  0.113281  0.112723  0.112723   0.087582  105728000
3 1980-12-17  0.115513  0.116071  0.115513  0.115513   0.089749   86441600
4 1980-12-18  0.118862  0.119420  0.118862  0.118862   0.092351   73449600

In [325]:
AAPL.info()  # 查看数据类型和缺失值情况

<class 'pandas.DataFrame'>
RangeIndex: 10665 entries, 0 to 10664
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       10665 non-null  datetime64[us]
 1   Open       10665 non-null  float64
 2   High       10665 non-null  float64
 3   Low        10665 non-null  float64
 4   Close      10665 non-null  float64
 5   Adj Close  10665 non-null  float64
 6   Volume     10665 non-null  int64
dtypes: datetime64[us](1), float64(5), int64(1)
memory usage: 583.4 KB

In [326]:
AAPL['Date'].dt.year  # 使用dt属性访问年份

0        1980
1        1980
2        1980
3        1980
4        1980
         ...
10660    2023
10661    2023
10662    2023
10663    2023
10664    2023
Name: Date, Length: 10665, dtype: int32

In [327]:
AAPL['Date'].dt.is_month_start  # 使用dt属性访问是否为月初

0        False
1        False
2        False
3        False
4        False
         ...
10660    False
10661    False
10662    False
10663    False
10664    False
Name: Date, Length: 10665, dtype: bool

## 1.6 重采样

pandas有一个虽然简单但非常强大的功能，可在频率转换时执行重采样，如，将秒数据转换为分钟数据，或者将日数据转换为月数据。<br>

resample()函数是基于时间序列的groupby()函数，每个组都遵循归纳方法。

resample（）可以直接用于dataframegroupby()函数

> 注意：重采样一定要以时间类型做index

In [329]:
aapl

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
1980-12-12,0.128348,0.128906,0.128348,0.128348,0.099722,469033600
1980-12-15,0.122210,0.122210,0.121652,0.121652,0.094519,175884800
1980-12-16,0.113281,0.113281,0.112723,0.112723,0.087582,105728000
1980-12-17,0.115513,0.116071,0.115513,0.115513,0.089749,86441600
1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092351,73449600
...,...,...,...,...,...,...
2023-03-27,159.940002,160.770004,157.869995,158.279999,158.279999,52390300
2023-03-28,157.970001,158.490005,155.979996,157.649994,157.649994,45992200
2023-03-29,159.369995,161.050003,159.350006,160.770004,160.770004,51305700
2023-03-30,161.529999,162.470001,161.270004,162.360001,162.360001,49501700
2023-03-31,162.440002,165.000000,161.910004,164.899994,164.899994,68694700

In [336]:
aapl.resample('YE')['Open'].mean() # 按年重采样，计算每年的平均值

Date
1980-12-31      0.136075
1981-12-31      0.108883
1982-12-31      0.085446
1983-12-31      0.167274
1984-12-31      0.119956
1985-12-31      0.091057
1986-12-31      0.144586
1987-12-31      0.347817
1988-12-31      0.371034
1989-12-31      0.371563
1990-12-31      0.334839
1991-12-31      0.468318
1992-12-31      0.489318
1993-12-31      0.366636
1994-12-31      0.304040
1995-12-31      0.362706
1996-12-31      0.223641
1997-12-31      0.161005
1998-12-31      0.272430
1999-12-31      0.514817
2000-12-31      0.817692
2001-12-31      0.360094
2002-12-31      0.341572
2003-12-31      0.330746
2004-12-31      0.632526
2005-12-31      1.665373
2006-12-31      2.535272
2007-12-31      4.585324
2008-12-31      5.082634
2009-12-31      5.236396
2010-12-31      9.284201
2011-12-31     13.002194
2012-12-31     20.594740
2013-12-31     16.897433
2014-12-31     23.054958
2015-12-31     30.043938
2016-12-31     26.126944
2017-12-31     37.611225
2018-12-31     47.277859
2019-12-31     51.967272
2020-12-31     95.267668
2021-12-31    140.861866
2022-12-31    154.802709
2023-12-31    146.924033
Freq: YE-DEC, Name: Open, dtype: float64

In [337]:
# 每三年平均开盘价
aapl.resample('3YE')['Open'].mean() # 按三年重采样，计算每三年的平均值

Date
1980-12-31      0.136075
1983-12-31      0.120534
1986-12-31      0.118569
1989-12-31      0.363461
1992-12-31      0.430902
1995-12-31      0.344490
1998-12-31      0.218961
2001-12-31      0.565287
2004-12-31      0.434948
2007-12-31      2.926981
2010-12-31      6.532492
2013-12-31     16.821474
2016-12-31     26.408613
2019-12-31     45.627205
2022-12-31    130.231998
2025-12-31    146.924033
Freq: 3YE-DEC, Name: Open, dtype: float64

In [338]:
# 每450的平均开盘价
aapl.resample('450D')['Open'].mean() # 按450天重采样，计算每450天的平均值

Date
1980-12-12      0.106801
1982-03-07      0.122024
1983-05-31      0.134137
1984-08-23      0.098225
1985-11-16      0.145833
1987-02-09      0.365935
1988-05-04      0.364573
1989-07-28      0.353995
1990-10-21      0.447847
1992-01-14      0.491546
1993-04-08      0.304580
1994-07-02      0.353074
1995-09-25      0.247461
1996-12-18      0.164826
1998-03-13      0.314532
1999-06-06      0.815261
2000-08-29      0.400822
2001-11-22      0.336538
2003-02-15      0.370738
2004-05-10      1.046164
2005-08-03      2.295633
2006-10-27      4.442360
2008-01-20      4.656594
2009-04-14      6.925207
2010-07-08     11.707567
2011-10-01     19.281180
2012-12-24     17.274409
2014-03-19     26.595235
2015-06-12     26.991744
2016-09-04     34.722927
2017-11-28     46.154399
2019-02-21     59.410665
2020-05-16    119.968229
2021-08-09    156.276923
2022-11-02    144.998641
Freq: 450D, Name: Open, dtype: float64

## 1.7 时间差

Timedelta（）:时间差对象，表示两个时间点之间的差值。可以通过减法运算符（-）计算两个时间戳之间的差值，返回一个Timedelta对象。

In [339]:
now = pd.Timestamp.now()  # 获取当前时间戳

In [340]:
now

Timestamp('2026-07-16 15:45:41.477987')

In [344]:
delta = pd.Timedelta(4, unit='D')  # 创建一个表示4天的时间差对象
delta

Timedelta('4 days 00:00:00')

In [346]:
now + delta

Timestamp('2026-07-20 15:45:41.477987')

In [351]:
delta = pd.Timedelta(days=4, hours=3, minutes=30)  # 创建一个表示4天3小时30分钟的时间差对象
delta

Timedelta('4 days 03:30:00')

In [352]:
now + delta

Timestamp('2026-07-20 19:15:41.477987')

以时间差为数据的Series和DataFrame对象支持各种运算，datetime64[ns]序列或Timestamps减法运算生成的是timedelta64[ns]序列。

In [353]:
s = pd.Series(data = pd.date_range(start='2023-01-01', periods=5, freq='D'))  # 创建一个以时间戳为数据的Series对象

In [354]:
d = pd.Series(data = [pd.Timedelta(days=i) for i in range(5)])  # 创建一个以时间差为数据的Series对象

In [360]:
df = pd.DataFrame(data = {'date': s, 'delta': d})  # 创建一个包含时间戳和时间差的DataFrame对象
df

        date  delta
0 2023-01-01 0 days
1 2023-01-02 1 days
2 2023-01-03 2 days
3 2023-01-04 3 days
4 2023-01-05 4 days

In [362]:
df['new_date'] = df['date'] + df['delta']  # 将时间戳和时间差相加，得到新的时间戳

In [363]:
df

        date  delta   new_date
0 2023-01-01 0 days 2023-01-01
1 2023-01-02 1 days 2023-01-03
2 2023-01-03 2 days 2023-01-05
3 2023-01-04 3 days 2023-01-07
4 2023-01-05 4 days 2023-01-09

In [364]:
s

0   2023-01-01
1   2023-01-02
2   2023-01-03
3   2023-01-04
4   2023-01-05
dtype: datetime64[us]

In [366]:
s.max()

Timestamp('2023-01-05 00:00:00')